// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_logos.sql

package sqlcgen

import (
	"context"
	"time"
)

const createApplicationLogo = `-- name: CreateApplicationLogo :exec
INSERT INTO application_logos (
    id, tenant_id, content_type, bytes, sha256, byte_size, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateApplicationLogoParams struct {
	ID          string
	TenantID    string
	ContentType string
	Bytes       []byte
	Sha256      string
	ByteSize    int32
	CreatedAt   time.Time
}

func (q *Queries) CreateApplicationLogo(ctx context.Context, arg CreateApplicationLogoParams) error {
	_, err := q.db.ExecContext(ctx, createApplicationLogo,
		arg.ID,
		arg.TenantID,
		arg.ContentType,
		arg.Bytes,
		arg.Sha256,
		arg.ByteSize,
		arg.CreatedAt,
	)
	return err
}

const deleteOrphanedApplicationLogos = `-- name: DeleteOrphanedApplicationLogos :execrows
DELETE FROM application_logos
WHERE application_logos.tenant_id = $1
  AND application_logos.created_at < $2
  AND NOT EXISTS (
      SELECT 1 FROM oauth_clients c
      WHERE c.tenant_id = application_logos.tenant_id
        AND c.logo_uri LIKE '%/logos/' || application_logos.id
  )
  AND NOT EXISTS (
      SELECT 1 FROM saml_service_providers p
      WHERE p.tenant_id = application_logos.tenant_id
        AND p.logo_uri LIKE '%/logos/' || application_logos.id
  )
  AND NOT EXISTS (
      SELECT 1 FROM cas_services s
      WHERE s.tenant_id = application_logos.tenant_id
        AND s.logo_uri LIKE '%/logos/' || application_logos.id
  )
`

type DeleteOrphanedApplicationLogosParams struct {
	TenantID  string
	CreatedAt time.Time
}

// Orphans: uploaded, old enough that the form which would have referenced them
// is long gone, and named by none of the three application tables.
//
// An upload has to be stored before the registration form is saved, so
// cancelling that form strands a row, and changing a logo strands the one it
// replaced. The alternative to sweeping is reference counting across three
// tables, which is more machinery than a few kilobytes deserves.
//
// The paths are matched by suffix rather than reconstructed, because the column
// holds whatever was written into it and this query should not have to know how
// the mount is spelled.
func (q *Queries) DeleteOrphanedApplicationLogos(ctx context.Context, arg DeleteOrphanedApplicationLogosParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanedApplicationLogos, arg.TenantID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getApplicationLogo = `-- name: GetApplicationLogo :one
SELECT id, tenant_id, content_type, bytes, sha256, byte_size, created_at FROM application_logos
WHERE tenant_id = $1 AND id = $2
`

type GetApplicationLogoParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetApplicationLogo(ctx context.Context, arg GetApplicationLogoParams) (ApplicationLogo, error) {
	row := q.db.QueryRowContext(ctx, getApplicationLogo, arg.TenantID, arg.ID)
	var i ApplicationLogo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContentType,
		&i.Bytes,
		&i.Sha256,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}
