// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    id, tenant_id, kind, action, actor_id, actor_username,
    target_type, target_id, target_name,
    result, detail, ip, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateAuditLogParams struct {
	ID            string
	TenantID      string
	Kind          string
	Action        string
	ActorID       *string
	ActorUsername string
	TargetType    string
	TargetID      string
	TargetName    string
	Result        string
	Detail        string
	Ip            string
	CreatedAt     time.Time
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.TenantID,
		arg.Kind,
		arg.Action,
		arg.ActorID,
		arg.ActorUsername,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.Result,
		arg.Detail,
		arg.Ip,
		arg.CreatedAt,
	)
	return err
}

const deleteAuditLogsBefore = `-- name: DeleteAuditLogsBefore :exec
DELETE FROM audit_logs WHERE tenant_id = $1 AND created_at < $2
`

type DeleteAuditLogsBeforeParams struct {
	TenantID  string
	CreatedAt time.Time
}

// Removes entries older than a cutoff.
//
// Only ever called when a tenant has configured a retention period. There is
// no default cutoff and no automatic one: an audit trail that quietly
// shortens itself is doing the worst thing an audit trail can do, so the
// decision belongs to whoever runs the deployment and has to be made
// explicitly.
func (q *Queries) DeleteAuditLogsBefore(ctx context.Context, arg DeleteAuditLogsBeforeParams) error {
	_, err := q.db.ExecContext(ctx, deleteAuditLogsBefore, arg.TenantID, arg.CreatedAt)
	return err
}
