// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    id, kind, action, actor_id, actor_username,
    target_type, target_id, target_name,
    result, detail, ip, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateAuditLogParams struct {
	ID            string
	Kind          string
	Action        string
	ActorID       *string
	ActorUsername string
	TargetType    string
	TargetID      string
	TargetName    string
	Result        string
	Detail        string
	Ip            string
	CreatedAt     time.Time
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.Kind,
		arg.Action,
		arg.ActorID,
		arg.ActorUsername,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.Result,
		arg.Detail,
		arg.Ip,
		arg.CreatedAt,
	)
	return err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, kind, action, actor_id, actor_username, target_type, target_id, target_name, result, detail, ip, created_at FROM audit_logs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id string) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Action,
		&i.ActorID,
		&i.ActorUsername,
		&i.TargetType,
		&i.TargetID,
		&i.TargetName,
		&i.Result,
		&i.Detail,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}
