// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authentication.sql

package sqlcgen

import (
	"context"
)

const getUserForAuthentication = `-- name: GetUserForAuthentication :one

SELECT id, tenant_id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, external_id, failed_login_attempts, last_failed_login_at, locked_until, password_changed_at, created_at, updated_at, ldap_source_id, closed_at FROM users WHERE id = $1 LIMIT 1
`

// The one query on a tenant-scoped table that is not itself tenant-scoped.
//
// It runs before the tenant is known: a bearer token identifies a user, and
// this read is how the tenant that user belongs to is established. Filtering
// it by tenant would be circular.
//
// Two things keep it from being a hole. The caller compares the row's
// tenant_id against the tid claim in the token and rejects a mismatch, so a
// token cannot be replayed against a tenant it was not issued for. And
// TestExactlyOneUnscopedQueryIsAllowed asserts that this is the only unscoped read of a
// scoped table — adding a second one fails the build rather than passing
// review unnoticed.
func (q *Queries) GetUserForAuthentication(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserForAuthentication, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.OrganizationID,
		&i.TokenVersion,
		&i.Source,
		&i.ExternalID,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LdapSourceID,
		&i.ClosedAt,
	)
	return i, err
}
