// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cas.sql

package sqlcgen

import (
	"context"
	"time"
)

const consumeCASTicket = `-- name: ConsumeCASTicket :one
UPDATE cas_tickets
SET consumed_at = $1
WHERE tenant_id = $2
  AND ticket_hash = $3
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, tenant_id, ticket_hash, service, subject, consumed_at, created_at, expires_at
`

type ConsumeCASTicketParams struct {
	ConsumedAt *time.Time
	TenantID   string
	TicketHash string
}

// Single use, as one statement. A read followed by a write would let two
// validations of the same ticket both see it unconsumed and both succeed,
// which is the whole property a service ticket has.
func (q *Queries) ConsumeCASTicket(ctx context.Context, arg ConsumeCASTicketParams) (CasTicket, error) {
	row := q.db.QueryRowContext(ctx, consumeCASTicket, arg.ConsumedAt, arg.TenantID, arg.TicketHash)
	var i CasTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TicketHash,
		&i.Service,
		&i.Subject,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createCASService = `-- name: CreateCASService :exec
INSERT INTO cas_services (
    id, tenant_id, name, url_prefix, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCASServiceParams struct {
	ID        string
	TenantID  string
	Name      string
	UrlPrefix string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateCASService(ctx context.Context, arg CreateCASServiceParams) error {
	_, err := q.db.ExecContext(ctx, createCASService,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.UrlPrefix,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createCASTicket = `-- name: CreateCASTicket :exec
INSERT INTO cas_tickets (
    id, tenant_id, ticket_hash, service, subject, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCASTicketParams struct {
	ID         string
	TenantID   string
	TicketHash string
	Service    string
	Subject    string
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

func (q *Queries) CreateCASTicket(ctx context.Context, arg CreateCASTicketParams) error {
	_, err := q.db.ExecContext(ctx, createCASTicket,
		arg.ID,
		arg.TenantID,
		arg.TicketHash,
		arg.Service,
		arg.Subject,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredCASTickets = `-- name: DeleteExpiredCASTickets :exec
DELETE FROM cas_tickets WHERE tenant_id = $1 AND expires_at < $2
`

type DeleteExpiredCASTicketsParams struct {
	TenantID  string
	ExpiresAt time.Time
}

func (q *Queries) DeleteExpiredCASTickets(ctx context.Context, arg DeleteExpiredCASTicketsParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCASTickets, arg.TenantID, arg.ExpiresAt)
	return err
}

const getCASService = `-- name: GetCASService :one
SELECT id, tenant_id, name, url_prefix, status, created_at, updated_at FROM cas_services
WHERE tenant_id = $1 AND url_prefix = $2
LIMIT 1
`

type GetCASServiceParams struct {
	TenantID  string
	UrlPrefix string
}

func (q *Queries) GetCASService(ctx context.Context, arg GetCASServiceParams) (CasService, error) {
	row := q.db.QueryRowContext(ctx, getCASService, arg.TenantID, arg.UrlPrefix)
	var i CasService
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.UrlPrefix,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCASServiceByID = `-- name: GetCASServiceByID :one
SELECT id, tenant_id, name, url_prefix, status, created_at, updated_at FROM cas_services
WHERE tenant_id = $1 AND id = $2
LIMIT 1
`

type GetCASServiceByIDParams struct {
	TenantID string
	ID       string
}

// Looked up by id for the same reason as a SAML service provider: a URL
// prefix in a path has to be percent-encoded, and a normalizing proxy
// decodes it.
func (q *Queries) GetCASServiceByID(ctx context.Context, arg GetCASServiceByIDParams) (CasService, error) {
	row := q.db.QueryRowContext(ctx, getCASServiceByID, arg.TenantID, arg.ID)
	var i CasService
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.UrlPrefix,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCASServices = `-- name: ListCASServices :many
SELECT id, tenant_id, name, url_prefix, status, created_at, updated_at FROM cas_services
WHERE tenant_id = $1
ORDER BY url_prefix
`

func (q *Queries) ListCASServices(ctx context.Context, tenantID string) ([]CasService, error) {
	rows, err := q.db.QueryContext(ctx, listCASServices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CasService{}
	for rows.Next() {
		var i CasService
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.UrlPrefix,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCASService = `-- name: UpdateCASService :exec
UPDATE cas_services
SET name = $1, url_prefix = $2, updated_at = $3
WHERE tenant_id = $4 AND url_prefix = $5
`

type UpdateCASServiceParams struct {
	Name        string
	UrlPrefix   string
	UpdatedAt   time.Time
	TenantID    string
	UrlPrefix_2 string
}

// Matched on the old prefix and able to set a new one, because a prefix is
// a deployment address rather than an identity: an application that moves to
// a new host has to be editable, or the only way to follow it is to
// de-register and re-register.
func (q *Queries) UpdateCASService(ctx context.Context, arg UpdateCASServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateCASService,
		arg.Name,
		arg.UrlPrefix,
		arg.UpdatedAt,
		arg.TenantID,
		arg.UrlPrefix_2,
	)
	return err
}

const updateCASServiceStatus = `-- name: UpdateCASServiceStatus :exec
UPDATE cas_services
SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND url_prefix = $4
`

type UpdateCASServiceStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	UrlPrefix string
}

func (q *Queries) UpdateCASServiceStatus(ctx context.Context, arg UpdateCASServiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCASServiceStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.UrlPrefix,
	)
	return err
}
