// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_idp.sql

package sqlcgen

import (
	"context"
	"time"
)

const countExternalIdentitiesForProvider = `-- name: CountExternalIdentitiesForProvider :one
SELECT count(*) FROM external_identities
WHERE tenant_id = $1 AND provider_id = $2
`

type CountExternalIdentitiesForProviderParams struct {
	TenantID   string
	ProviderID string
}

func (q *Queries) CountExternalIdentitiesForProvider(ctx context.Context, arg CountExternalIdentitiesForProviderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExternalIdentitiesForProvider, arg.TenantID, arg.ProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExternalIdentity = `-- name: CreateExternalIdentity :exec
INSERT INTO external_identities (
    id, tenant_id, provider_id, user_id, subject, email, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateExternalIdentityParams struct {
	ID         string
	TenantID   string
	ProviderID string
	UserID     string
	Subject    string
	Email      string
	CreatedAt  time.Time
}

func (q *Queries) CreateExternalIdentity(ctx context.Context, arg CreateExternalIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createExternalIdentity,
		arg.ID,
		arg.TenantID,
		arg.ProviderID,
		arg.UserID,
		arg.Subject,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const createExternalIdentityProvider = `-- name: CreateExternalIdentityProvider :exec
INSERT INTO external_identity_providers (
    id, tenant_id, name, button_label, issuer, client_id, client_secret,
    scopes, trust_verified_email, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'ACTIVE', $10, $10)
`

type CreateExternalIdentityProviderParams struct {
	ID                 string
	TenantID           string
	Name               string
	ButtonLabel        string
	Issuer             string
	ClientID           string
	ClientSecret       string
	Scopes             string
	TrustVerifiedEmail bool
	CreatedAt          time.Time
}

func (q *Queries) CreateExternalIdentityProvider(ctx context.Context, arg CreateExternalIdentityProviderParams) error {
	_, err := q.db.ExecContext(ctx, createExternalIdentityProvider,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ButtonLabel,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.TrustVerifiedEmail,
		arg.CreatedAt,
	)
	return err
}

const deleteExternalIdentity = `-- name: DeleteExternalIdentity :exec
DELETE FROM external_identities
WHERE tenant_id = $1 AND user_id = $2 AND id = $3
`

type DeleteExternalIdentityParams struct {
	TenantID string
	UserID   string
	ID       string
}

func (q *Queries) DeleteExternalIdentity(ctx context.Context, arg DeleteExternalIdentityParams) error {
	_, err := q.db.ExecContext(ctx, deleteExternalIdentity, arg.TenantID, arg.UserID, arg.ID)
	return err
}

const deleteExternalIdentityProvider = `-- name: DeleteExternalIdentityProvider :exec
DELETE FROM external_identity_providers WHERE tenant_id = $1 AND id = $2
`

type DeleteExternalIdentityProviderParams struct {
	TenantID string
	ID       string
}

// The bindings go with it, by cascade. Deliberate: an identity that names a
// provider nobody can reach is not a credential, and leaving the rows would
// mean a re-added provider silently inheriting who was bound to the old one.
func (q *Queries) DeleteExternalIdentityProvider(ctx context.Context, arg DeleteExternalIdentityProviderParams) error {
	_, err := q.db.ExecContext(ctx, deleteExternalIdentityProvider, arg.TenantID, arg.ID)
	return err
}

const getExternalIdentity = `-- name: GetExternalIdentity :one
SELECT id, tenant_id, provider_id, user_id, subject, email, created_at, last_used_at FROM external_identities
WHERE tenant_id = $1 AND provider_id = $2 AND subject = $3
`

type GetExternalIdentityParams struct {
	TenantID   string
	ProviderID string
	Subject    string
}

// The whole point of the pair: a subject is unique inside its issuer and
// nowhere else.
func (q *Queries) GetExternalIdentity(ctx context.Context, arg GetExternalIdentityParams) (ExternalIdentity, error) {
	row := q.db.QueryRowContext(ctx, getExternalIdentity, arg.TenantID, arg.ProviderID, arg.Subject)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.UserID,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getExternalIdentityProvider = `-- name: GetExternalIdentityProvider :one
SELECT id, tenant_id, name, button_label, issuer, client_id, client_secret, scopes, trust_verified_email, status, created_at, updated_at FROM external_identity_providers WHERE tenant_id = $1 AND id = $2
`

type GetExternalIdentityProviderParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetExternalIdentityProvider(ctx context.Context, arg GetExternalIdentityProviderParams) (ExternalIdentityProvider, error) {
	row := q.db.QueryRowContext(ctx, getExternalIdentityProvider, arg.TenantID, arg.ID)
	var i ExternalIdentityProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ButtonLabel,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.TrustVerifiedEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveExternalIdentityProviders = `-- name: ListActiveExternalIdentityProviders :many
SELECT id, tenant_id, name, button_label, issuer, client_id, client_secret, scopes, trust_verified_email, status, created_at, updated_at FROM external_identity_providers
WHERE tenant_id = $1 AND status = 'ACTIVE' ORDER BY name
`

// What the sign-in screen offers. A disabled provider is not a button:
// somebody switched it off, and offering it would mean a person picks it and
// is refused after a round trip to somebody else's login page.
func (q *Queries) ListActiveExternalIdentityProviders(ctx context.Context, tenantID string) ([]ExternalIdentityProvider, error) {
	rows, err := q.db.QueryContext(ctx, listActiveExternalIdentityProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalIdentityProvider{}
	for rows.Next() {
		var i ExternalIdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ButtonLabel,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.TrustVerifiedEmail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalIdentitiesForUser = `-- name: ListExternalIdentitiesForUser :many
SELECT id, tenant_id, provider_id, user_id, subject, email, created_at, last_used_at FROM external_identities
WHERE tenant_id = $1 AND user_id = $2 ORDER BY created_at
`

type ListExternalIdentitiesForUserParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) ListExternalIdentitiesForUser(ctx context.Context, arg ListExternalIdentitiesForUserParams) ([]ExternalIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listExternalIdentitiesForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalIdentity{}
	for rows.Next() {
		var i ExternalIdentity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderID,
			&i.UserID,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalIdentityProviders = `-- name: ListExternalIdentityProviders :many
SELECT id, tenant_id, name, button_label, issuer, client_id, client_secret, scopes, trust_verified_email, status, created_at, updated_at FROM external_identity_providers
WHERE tenant_id = $1 ORDER BY name
`

// Every provider a tenant has configured, enabled or not.
func (q *Queries) ListExternalIdentityProviders(ctx context.Context, tenantID string) ([]ExternalIdentityProvider, error) {
	rows, err := q.db.QueryContext(ctx, listExternalIdentityProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalIdentityProvider{}
	for rows.Next() {
		var i ExternalIdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ButtonLabel,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.TrustVerifiedEmail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExternalIdentityProviderStatus = `-- name: SetExternalIdentityProviderStatus :exec
UPDATE external_identity_providers
SET status = $3, updated_at = $4 WHERE tenant_id = $1 AND id = $2
`

type SetExternalIdentityProviderStatusParams struct {
	TenantID  string
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) SetExternalIdentityProviderStatus(ctx context.Context, arg SetExternalIdentityProviderStatusParams) error {
	_, err := q.db.ExecContext(ctx, setExternalIdentityProviderStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const touchExternalIdentity = `-- name: TouchExternalIdentity :exec
UPDATE external_identities SET last_used_at = $4
WHERE tenant_id = $1 AND provider_id = $2 AND subject = $3
`

type TouchExternalIdentityParams struct {
	TenantID   string
	ProviderID string
	Subject    string
	LastUsedAt *time.Time
}

func (q *Queries) TouchExternalIdentity(ctx context.Context, arg TouchExternalIdentityParams) error {
	_, err := q.db.ExecContext(ctx, touchExternalIdentity,
		arg.TenantID,
		arg.ProviderID,
		arg.Subject,
		arg.LastUsedAt,
	)
	return err
}

const updateExternalIdentityProvider = `-- name: UpdateExternalIdentityProvider :exec
UPDATE external_identity_providers
SET name = $1,
    button_label = $2,
    issuer = $3,
    client_id = $4,
    client_secret = CASE WHEN $5::text = ''
                         THEN client_secret ELSE $5::text END,
    scopes = $6,
    trust_verified_email = $7,
    updated_at = $8::timestamptz
WHERE tenant_id = $9 AND id = $10
`

type UpdateExternalIdentityProviderParams struct {
	Name               string
	ButtonLabel        string
	Issuer             string
	ClientID           string
	ClientSecret       string
	Scopes             string
	TrustVerifiedEmail bool
	Now                time.Time
	TenantID           string
	ID                 string
}

// The secret is replaced only when a new one was given: an edit that left
// the field blank means "leave it alone", because the console never shows
// what is stored and a blank field is what an operator sees every time.
func (q *Queries) UpdateExternalIdentityProvider(ctx context.Context, arg UpdateExternalIdentityProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateExternalIdentityProvider,
		arg.Name,
		arg.ButtonLabel,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.TrustVerifiedEmail,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}
