// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: field_mappings.sql

package sqlcgen

import (
	"context"
	"time"
)

const createFieldMapping = `-- name: CreateFieldMapping :exec
INSERT INTO field_mappings (
    id, tenant_id,
    oauth_client_id, saml_sp_id, cas_service_id, webhook_subscription_id,
    source_key, target_name, friendly_name, suppressed, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateFieldMappingParams struct {
	ID                    string
	TenantID              string
	OauthClientID         *string
	SamlSpID              *string
	CasServiceID          *string
	WebhookSubscriptionID *string
	SourceKey             string
	TargetName            string
	FriendlyName          string
	Suppressed            bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) CreateFieldMapping(ctx context.Context, arg CreateFieldMappingParams) error {
	_, err := q.db.ExecContext(ctx, createFieldMapping,
		arg.ID,
		arg.TenantID,
		arg.OauthClientID,
		arg.SamlSpID,
		arg.CasServiceID,
		arg.WebhookSubscriptionID,
		arg.SourceKey,
		arg.TargetName,
		arg.FriendlyName,
		arg.Suppressed,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFieldMappings = `-- name: DeleteFieldMappings :exec
DELETE FROM field_mappings
WHERE tenant_id = $1
  AND oauth_client_id IS NOT DISTINCT FROM $2
  AND saml_sp_id IS NOT DISTINCT FROM $3
  AND cas_service_id IS NOT DISTINCT FROM $4
  AND webhook_subscription_id IS NOT DISTINCT FROM $5
`

type DeleteFieldMappingsParams struct {
	TenantID              string
	OauthClientID         *string
	SamlSpID              *string
	CasServiceID          *string
	WebhookSubscriptionID *string
}

// Clears one recipient's set. A save replaces the whole set rather than
// upserting row by row, because that is what the form is: a table somebody
// edited. Row-by-row would need four different ON CONFLICT targets and would
// leave whatever the form deleted still in place.
func (q *Queries) DeleteFieldMappings(ctx context.Context, arg DeleteFieldMappingsParams) error {
	_, err := q.db.ExecContext(ctx, deleteFieldMappings,
		arg.TenantID,
		arg.OauthClientID,
		arg.SamlSpID,
		arg.CasServiceID,
		arg.WebhookSubscriptionID,
	)
	return err
}

const listFieldMappings = `-- name: ListFieldMappings :many
SELECT id, tenant_id, oauth_client_id, saml_sp_id, cas_service_id, webhook_subscription_id, source_key, target_name, friendly_name, suppressed, created_at, updated_at FROM field_mappings
WHERE tenant_id = $1
  AND oauth_client_id IS NOT DISTINCT FROM $2
  AND saml_sp_id IS NOT DISTINCT FROM $3
  AND cas_service_id IS NOT DISTINCT FROM $4
  AND webhook_subscription_id IS NOT DISTINCT FROM $5
ORDER BY source_key
`

type ListFieldMappingsParams struct {
	TenantID              string
	OauthClientID         *string
	SamlSpID              *string
	CasServiceID          *string
	WebhookSubscriptionID *string
}

// One recipient's mappings. The caller passes the id of whichever kind of
// recipient it has and nulls for the other three; IS NOT DISTINCT FROM matches
// the null columns, and the CHECK constraint guarantees that identifies exactly
// one recipient rather than a set.
func (q *Queries) ListFieldMappings(ctx context.Context, arg ListFieldMappingsParams) ([]FieldMapping, error) {
	rows, err := q.db.QueryContext(ctx, listFieldMappings,
		arg.TenantID,
		arg.OauthClientID,
		arg.SamlSpID,
		arg.CasServiceID,
		arg.WebhookSubscriptionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FieldMapping{}
	for rows.Next() {
		var i FieldMapping
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OauthClientID,
			&i.SamlSpID,
			&i.CasServiceID,
			&i.WebhookSubscriptionID,
			&i.SourceKey,
			&i.TargetName,
			&i.FriendlyName,
			&i.Suppressed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipientsMappingField = `-- name: ListRecipientsMappingField :many
SELECT id, tenant_id, oauth_client_id, saml_sp_id, cas_service_id, webhook_subscription_id, source_key, target_name, friendly_name, suppressed, created_at, updated_at FROM field_mappings
WHERE tenant_id = $1 AND source_key = $2 AND suppressed = FALSE
`

type ListRecipientsMappingFieldParams struct {
	TenantID  string
	SourceKey string
}

// Which recipients receive one fact, across all four kinds at once. This is the
// disclosure question — "who gets department" — and answering it in one query
// is most of why they share a table.
func (q *Queries) ListRecipientsMappingField(ctx context.Context, arg ListRecipientsMappingFieldParams) ([]FieldMapping, error) {
	rows, err := q.db.QueryContext(ctx, listRecipientsMappingField, arg.TenantID, arg.SourceKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FieldMapping{}
	for rows.Next() {
		var i FieldMapping
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OauthClientID,
			&i.SamlSpID,
			&i.CasServiceID,
			&i.WebhookSubscriptionID,
			&i.SourceKey,
			&i.TargetName,
			&i.FriendlyName,
			&i.Suppressed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
