// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: field_mappings.sql

package sqlcgen

import (
	"context"
	"time"
)

const createApplicationFieldMapping = `-- name: CreateApplicationFieldMapping :exec
INSERT INTO application_field_mappings (
    id, tenant_id, oauth_client_id, saml_sp_id, cas_service_id,
    source_key, target_name, friendly_name, suppressed, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateApplicationFieldMappingParams struct {
	ID            string
	TenantID      string
	OauthClientID *string
	SamlSpID      *string
	CasServiceID  *string
	SourceKey     string
	TargetName    string
	FriendlyName  string
	Suppressed    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateApplicationFieldMapping(ctx context.Context, arg CreateApplicationFieldMappingParams) error {
	_, err := q.db.ExecContext(ctx, createApplicationFieldMapping,
		arg.ID,
		arg.TenantID,
		arg.OauthClientID,
		arg.SamlSpID,
		arg.CasServiceID,
		arg.SourceKey,
		arg.TargetName,
		arg.FriendlyName,
		arg.Suppressed,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteApplicationFieldMappings = `-- name: DeleteApplicationFieldMappings :exec
DELETE FROM application_field_mappings
WHERE tenant_id = $1
  AND oauth_client_id IS NOT DISTINCT FROM $2
  AND saml_sp_id IS NOT DISTINCT FROM $3
  AND cas_service_id IS NOT DISTINCT FROM $4
`

type DeleteApplicationFieldMappingsParams struct {
	TenantID      string
	OauthClientID *string
	SamlSpID      *string
	CasServiceID  *string
}

// Clears one application's set. A save replaces the whole set rather than
// upserting row by row, because that is what the form is: a table somebody
// edited. Row-by-row would need three different ON CONFLICT targets and would
// leave whatever the form deleted still in place.
func (q *Queries) DeleteApplicationFieldMappings(ctx context.Context, arg DeleteApplicationFieldMappingsParams) error {
	_, err := q.db.ExecContext(ctx, deleteApplicationFieldMappings,
		arg.TenantID,
		arg.OauthClientID,
		arg.SamlSpID,
		arg.CasServiceID,
	)
	return err
}

const listApplicationFieldMappings = `-- name: ListApplicationFieldMappings :many
SELECT id, tenant_id, oauth_client_id, saml_sp_id, cas_service_id, source_key, target_name, friendly_name, suppressed, created_at, updated_at FROM application_field_mappings
WHERE tenant_id = $1
  AND oauth_client_id IS NOT DISTINCT FROM $2
  AND saml_sp_id IS NOT DISTINCT FROM $3
  AND cas_service_id IS NOT DISTINCT FROM $4
ORDER BY source_key
`

type ListApplicationFieldMappingsParams struct {
	TenantID      string
	OauthClientID *string
	SamlSpID      *string
	CasServiceID  *string
}

// One application's mappings. The caller passes the id of whichever kind of
// application it has and nulls for the other two; IS NOT DISTINCT FROM matches
// the null columns, and the CHECK constraint guarantees that identifies exactly
// one application rather than a set.
func (q *Queries) ListApplicationFieldMappings(ctx context.Context, arg ListApplicationFieldMappingsParams) ([]ApplicationFieldMapping, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationFieldMappings,
		arg.TenantID,
		arg.OauthClientID,
		arg.SamlSpID,
		arg.CasServiceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationFieldMapping{}
	for rows.Next() {
		var i ApplicationFieldMapping
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OauthClientID,
			&i.SamlSpID,
			&i.CasServiceID,
			&i.SourceKey,
			&i.TargetName,
			&i.FriendlyName,
			&i.Suppressed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsMappingField = `-- name: ListApplicationsMappingField :many
SELECT id, tenant_id, oauth_client_id, saml_sp_id, cas_service_id, source_key, target_name, friendly_name, suppressed, created_at, updated_at FROM application_field_mappings
WHERE tenant_id = $1 AND source_key = $2 AND suppressed = FALSE
`

type ListApplicationsMappingFieldParams struct {
	TenantID  string
	SourceKey string
}

// Which applications receive one fact, across all three protocols at once.
// This is the disclosure question — "who gets department" — and answering it in
// one query is most of why the three protocols share a table.
func (q *Queries) ListApplicationsMappingField(ctx context.Context, arg ListApplicationsMappingFieldParams) ([]ApplicationFieldMapping, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationsMappingField, arg.TenantID, arg.SourceKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationFieldMapping{}
	for rows.Next() {
		var i ApplicationFieldMapping
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OauthClientID,
			&i.SamlSpID,
			&i.CasServiceID,
			&i.SourceKey,
			&i.TargetName,
			&i.FriendlyName,
			&i.Suppressed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
