// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"
	"time"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (tenant_id, group_id, user_id, added_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, group_id, user_id) DO NOTHING
`

type AddGroupMemberParams struct {
	TenantID string
	GroupID  string
	UserID   string
	AddedAt  time.Time
}

// Idempotent: a directory re-sending a membership it already pushed is
// normal, and failing it would turn an ordinary reconciliation into an
// error the operator has to interpret.
func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember,
		arg.TenantID,
		arg.GroupID,
		arg.UserID,
		arg.AddedAt,
	)
	return err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) FROM group_members WHERE tenant_id = $1 AND group_id = $2
`

type CountGroupMembersParams struct {
	TenantID string
	GroupID  string
}

func (q *Queries) CountGroupMembers(ctx context.Context, arg CountGroupMembersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, arg.TenantID, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
SELECT COUNT(*) FROM groups WHERE tenant_id = $1
`

func (q *Queries) CountGroups(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (
    id, tenant_id, display_name, description, external_id, source,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
`

type CreateGroupParams struct {
	ID          string
	TenantID    string
	DisplayName string
	Description string
	ExternalID  *string
	Source      string
	CreatedAt   time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup,
		arg.ID,
		arg.TenantID,
		arg.DisplayName,
		arg.Description,
		arg.ExternalID,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE tenant_id = $1 AND id = $2
`

type DeleteGroupParams struct {
	TenantID string
	ID       string
}

// Deleted rather than disabled, unlike accounts and organizations.
//
// A group is a set, not a party the audit trail refers to: entries name the
// people and the actor, and a removed group leaves those readable. Keeping
// deleted groups would instead leave a list an administrator has to read
// past, and a directory that deletes and recreates one — which they do —
// would accumulate them.
func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, arg.TenantID, arg.ID)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, tenant_id, display_name, description, external_id, source, created_at, updated_at FROM groups WHERE tenant_id = $1 AND id = $2
`

type GetGroupParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, arg.TenantID, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.Description,
		&i.ExternalID,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByDisplayName = `-- name: GetGroupByDisplayName :one
SELECT id, tenant_id, display_name, description, external_id, source, created_at, updated_at FROM groups WHERE tenant_id = $1 AND display_name = $2
`

type GetGroupByDisplayNameParams struct {
	TenantID    string
	DisplayName string
}

func (q *Queries) GetGroupByDisplayName(ctx context.Context, arg GetGroupByDisplayNameParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByDisplayName, arg.TenantID, arg.DisplayName)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.Description,
		&i.ExternalID,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByExternalID = `-- name: GetGroupByExternalID :one
SELECT id, tenant_id, display_name, description, external_id, source, created_at, updated_at FROM groups WHERE tenant_id = $1 AND external_id = $2
`

type GetGroupByExternalIDParams struct {
	TenantID   string
	ExternalID *string
}

func (q *Queries) GetGroupByExternalID(ctx context.Context, arg GetGroupByExternalIDParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByExternalID, arg.TenantID, arg.ExternalID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.Description,
		&i.ExternalID,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT m.user_id, u.username, u.display_name
FROM group_members m
JOIN users u ON u.tenant_id = m.tenant_id AND u.id = m.user_id
WHERE m.tenant_id = $1 AND m.group_id = $2
ORDER BY u.username
`

type ListGroupMembersParams struct {
	TenantID string
	GroupID  string
}

type ListGroupMembersRow struct {
	UserID      string
	Username    string
	DisplayName string
}

// The username comes along because SCIM's member representation carries a
// display value, and fetching it per member would be a query per row.
func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, arg.TenantID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, tenant_id, display_name, description, external_id, source, created_at, updated_at FROM groups WHERE tenant_id = $1 ORDER BY display_name
`

func (q *Queries) ListGroups(ctx context.Context, tenantID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DisplayName,
			&i.Description,
			&i.ExternalID,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.display_name
FROM group_members m
JOIN groups g ON g.tenant_id = m.tenant_id AND g.id = m.group_id
WHERE m.tenant_id = $1 AND m.user_id = $2
ORDER BY g.display_name
`

type ListGroupsForUserParams struct {
	TenantID string
	UserID   string
}

type ListGroupsForUserRow struct {
	ID          string
	DisplayName string
}

func (q *Queries) ListGroupsForUser(ctx context.Context, arg ListGroupsForUserParams) ([]ListGroupsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForUserRow{}
	for rows.Next() {
		var i ListGroupsForUserRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsWithMemberCounts = `-- name: ListGroupsWithMemberCounts :many
SELECT g.id, g.tenant_id, g.display_name, g.description, g.external_id, g.source, g.created_at, g.updated_at, COUNT(m.user_id) AS member_count
FROM groups g
LEFT JOIN group_members m ON m.tenant_id = g.tenant_id AND m.group_id = g.id
WHERE g.tenant_id = $1
GROUP BY g.id
ORDER BY g.display_name
`

type ListGroupsWithMemberCountsRow struct {
	ID          string
	TenantID    string
	DisplayName string
	Description string
	ExternalID  *string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MemberCount int64
}

// One query for the console's list, rather than a count per group.
func (q *Queries) ListGroupsWithMemberCounts(ctx context.Context, tenantID string) ([]ListGroupsWithMemberCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsWithMemberCounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsWithMemberCountsRow{}
	for rows.Next() {
		var i ListGroupsWithMemberCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DisplayName,
			&i.Description,
			&i.ExternalID,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllGroupMembers = `-- name: RemoveAllGroupMembers :exec
DELETE FROM group_members WHERE tenant_id = $1 AND group_id = $2
`

type RemoveAllGroupMembersParams struct {
	TenantID string
	GroupID  string
}

// For PATCH replace, which hands over the whole membership at once.
func (q *Queries) RemoveAllGroupMembers(ctx context.Context, arg RemoveAllGroupMembersParams) error {
	_, err := q.db.ExecContext(ctx, removeAllGroupMembers, arg.TenantID, arg.GroupID)
	return err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE tenant_id = $1 AND group_id = $2 AND user_id = $3
`

type RemoveGroupMemberParams struct {
	TenantID string
	GroupID  string
	UserID   string
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.TenantID, arg.GroupID, arg.UserID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE groups
SET display_name = $1, description = $2, external_id = $3, updated_at = $4
WHERE tenant_id = $5 AND id = $6
`

type UpdateGroupParams struct {
	DisplayName string
	Description string
	ExternalID  *string
	UpdatedAt   time.Time
	TenantID    string
	ID          string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup,
		arg.DisplayName,
		arg.Description,
		arg.ExternalID,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}
