// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createInvitation = `-- name: CreateInvitation :exec
INSERT INTO invitations (
    id, tenant_id, code, organization_id, group_ids,
    quota, expires_at, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
`

type CreateInvitationParams struct {
	ID             string
	TenantID       string
	Code           string
	OrganizationID *string
	GroupIds       []string
	Quota          int32
	ExpiresAt      *time.Time
	Status         string
	CreatedAt      time.Time
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) error {
	_, err := q.db.ExecContext(ctx, createInvitation,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.OrganizationID,
		pq.Array(arg.GroupIds),
		arg.Quota,
		arg.ExpiresAt,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, tenant_id, code, organization_id, group_ids, quota, used_count, expires_at, status, created_at, updated_at FROM invitations WHERE tenant_id = $1 AND id = $2
`

type GetInvitationParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetInvitation(ctx context.Context, arg GetInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitation, arg.TenantID, arg.ID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.OrganizationID,
		pq.Array(&i.GroupIds),
		&i.Quota,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByCode = `-- name: GetInvitationByCode :one
SELECT id, tenant_id, code, organization_id, group_ids, quota, used_count, expires_at, status, created_at, updated_at FROM invitations WHERE tenant_id = $1 AND code = $2
`

type GetInvitationByCodeParams struct {
	TenantID string
	Code     string
}

func (q *Queries) GetInvitationByCode(ctx context.Context, arg GetInvitationByCodeParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByCode, arg.TenantID, arg.Code)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.OrganizationID,
		pq.Array(&i.GroupIds),
		&i.Quota,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, tenant_id, code, organization_id, group_ids, quota, used_count, expires_at, status, created_at, updated_at FROM invitations WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvitations(ctx context.Context, tenantID string) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listInvitations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.OrganizationID,
			pq.Array(&i.GroupIds),
			&i.Quota,
			&i.UsedCount,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInvitation = `-- name: RedeemInvitation :one
UPDATE invitations
SET used_count = used_count + 1, updated_at = $3
WHERE tenant_id = $1 AND id = $2
  AND status = 'ACTIVE' AND used_count < quota
RETURNING id, tenant_id, code, organization_id, group_ids, quota, used_count, expires_at, status, created_at, updated_at
`

type RedeemInvitationParams struct {
	TenantID  string
	ID        string
	UpdatedAt time.Time
}

// The atomic increment that makes concurrent redemption safe: a row comes
// back only if the invitation is ACTIVE and still has quota, and the check
// and the increment happen in the same statement, so two concurrent callers
// can never both observe used_count < quota and both commit. Expiry is
// checked by the caller against store.Now() before this runs, not here —
// this project compares against an application-supplied clock rather than
// the database's own NOW() so tests can control it (see store.Now()).
//
// This is deliberately not wrapped as a Scoped method (internal/store/scoped.go).
// It must only run inside the same store.WithTx transaction as the account
// creation it pays for; a non-transactional caller could redeem a code and
// then fail to create the account, leaving the redemption unrecoverable.
func (q *Queries) RedeemInvitation(ctx context.Context, arg RedeemInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, redeemInvitation, arg.TenantID, arg.ID, arg.UpdatedAt)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.OrganizationID,
		pq.Array(&i.GroupIds),
		&i.Quota,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :exec
UPDATE invitations SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateInvitationStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInvitationStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}
