// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ldap.sql

package sqlcgen

import (
	"context"
	"time"
)

const bindUserToLDAPSource = `-- name: BindUserToLDAPSource :exec
UPDATE users
SET ldap_source_id = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type BindUserToLDAPSourceParams struct {
	LdapSourceID *string
	UpdatedAt    time.Time
	TenantID     string
	ID           string
}

func (q *Queries) BindUserToLDAPSource(ctx context.Context, arg BindUserToLDAPSourceParams) error {
	_, err := q.db.ExecContext(ctx, bindUserToLDAPSource,
		arg.LdapSourceID,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const createLDAPSource = `-- name: CreateLDAPSource :exec
INSERT INTO ldap_sources (
    id, tenant_id, name, host, port, encryption,
    bind_dn, bind_password, base_dn, user_filter,
    attr_username, attr_display_name, attr_email, attr_phone, attr_external_id,
    organization_id, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19
)
`

type CreateLDAPSourceParams struct {
	ID              string
	TenantID        string
	Name            string
	Host            string
	Port            int32
	Encryption      string
	BindDn          string
	BindPassword    string
	BaseDn          string
	UserFilter      string
	AttrUsername    string
	AttrDisplayName string
	AttrEmail       string
	AttrPhone       string
	AttrExternalID  string
	OrganizationID  *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateLDAPSource(ctx context.Context, arg CreateLDAPSourceParams) error {
	_, err := q.db.ExecContext(ctx, createLDAPSource,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Encryption,
		arg.BindDn,
		arg.BindPassword,
		arg.BaseDn,
		arg.UserFilter,
		arg.AttrUsername,
		arg.AttrDisplayName,
		arg.AttrEmail,
		arg.AttrPhone,
		arg.AttrExternalID,
		arg.OrganizationID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const finishLDAPSyncRun = `-- name: FinishLDAPSyncRun :exec
UPDATE ldap_sync_runs
SET finished_at = $1,
    outcome = $2,
    created_count = $3,
    updated_count = $4,
    deactivated_count = $5,
    skipped_count = $6,
    error_code = $7,
    error = $8
WHERE tenant_id = $9 AND id = $10
`

type FinishLDAPSyncRunParams struct {
	FinishedAt       *time.Time
	Outcome          string
	CreatedCount     int32
	UpdatedCount     int32
	DeactivatedCount int32
	SkippedCount     int32
	ErrorCode        string
	Error            string
	TenantID         string
	ID               string
}

func (q *Queries) FinishLDAPSyncRun(ctx context.Context, arg FinishLDAPSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, finishLDAPSyncRun,
		arg.FinishedAt,
		arg.Outcome,
		arg.CreatedCount,
		arg.UpdatedCount,
		arg.DeactivatedCount,
		arg.SkippedCount,
		arg.ErrorCode,
		arg.Error,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const getLDAPSource = `-- name: GetLDAPSource :one
SELECT id, tenant_id, name, host, port, encryption, bind_dn, bind_password, base_dn, user_filter, attr_username, attr_display_name, attr_email, attr_phone, attr_external_id, organization_id, status, last_synced_at, created_at, updated_at FROM ldap_sources WHERE tenant_id = $1 AND id = $2 LIMIT 1
`

type GetLDAPSourceParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetLDAPSource(ctx context.Context, arg GetLDAPSourceParams) (LdapSource, error) {
	row := q.db.QueryRowContext(ctx, getLDAPSource, arg.TenantID, arg.ID)
	var i LdapSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Encryption,
		&i.BindDn,
		&i.BindPassword,
		&i.BaseDn,
		&i.UserFilter,
		&i.AttrUsername,
		&i.AttrDisplayName,
		&i.AttrEmail,
		&i.AttrPhone,
		&i.AttrExternalID,
		&i.OrganizationID,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLDAPSources = `-- name: ListLDAPSources :many
SELECT id, tenant_id, name, host, port, encryption, bind_dn, bind_password, base_dn, user_filter, attr_username, attr_display_name, attr_email, attr_phone, attr_external_id, organization_id, status, last_synced_at, created_at, updated_at FROM ldap_sources WHERE tenant_id = $1 ORDER BY created_at
`

func (q *Queries) ListLDAPSources(ctx context.Context, tenantID string) ([]LdapSource, error) {
	rows, err := q.db.QueryContext(ctx, listLDAPSources, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LdapSource{}
	for rows.Next() {
		var i LdapSource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Encryption,
			&i.BindDn,
			&i.BindPassword,
			&i.BaseDn,
			&i.UserFilter,
			&i.AttrUsername,
			&i.AttrDisplayName,
			&i.AttrEmail,
			&i.AttrPhone,
			&i.AttrExternalID,
			&i.OrganizationID,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLDAPSyncRuns = `-- name: ListLDAPSyncRuns :many
SELECT id, tenant_id, source_id, actor_name, started_at, finished_at, outcome, created_count, updated_count, deactivated_count, skipped_count, error_code, error FROM ldap_sync_runs
WHERE tenant_id = $1 AND source_id = $2
ORDER BY started_at DESC
LIMIT $3
`

type ListLDAPSyncRunsParams struct {
	TenantID string
	SourceID string
	Limit    int32
}

func (q *Queries) ListLDAPSyncRuns(ctx context.Context, arg ListLDAPSyncRunsParams) ([]LdapSyncRun, error) {
	rows, err := q.db.QueryContext(ctx, listLDAPSyncRuns, arg.TenantID, arg.SourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LdapSyncRun{}
	for rows.Next() {
		var i LdapSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.ActorName,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Outcome,
			&i.CreatedCount,
			&i.UpdatedCount,
			&i.DeactivatedCount,
			&i.SkippedCount,
			&i.ErrorCode,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersFromLDAPSource = `-- name: ListUsersFromLDAPSource :many
SELECT id, tenant_id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, external_id, failed_login_attempts, last_failed_login_at, locked_until, password_changed_at, created_at, updated_at, ldap_source_id, closed_at FROM users
WHERE tenant_id = $1 AND ldap_source_id = $2
`

type ListUsersFromLDAPSourceParams struct {
	TenantID     string
	LdapSourceID *string
}

// Every account this directory owns, which is what a sync compares against
// to work out what has vanished from it.
func (q *Queries) ListUsersFromLDAPSource(ctx context.Context, arg ListUsersFromLDAPSourceParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersFromLDAPSource, arg.TenantID, arg.LdapSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Phone,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.OrganizationID,
			&i.TokenVersion,
			&i.Source,
			&i.ExternalID,
			&i.FailedLoginAttempts,
			&i.LastFailedLoginAt,
			&i.LockedUntil,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LdapSourceID,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLDAPSourceSynced = `-- name: MarkLDAPSourceSynced :exec
UPDATE ldap_sources
SET last_synced_at = $1, updated_at = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkLDAPSourceSyncedParams struct {
	LastSyncedAt *time.Time
	TenantID     string
	ID           string
}

func (q *Queries) MarkLDAPSourceSynced(ctx context.Context, arg MarkLDAPSourceSyncedParams) error {
	_, err := q.db.ExecContext(ctx, markLDAPSourceSynced, arg.LastSyncedAt, arg.TenantID, arg.ID)
	return err
}

const startLDAPSyncRun = `-- name: StartLDAPSyncRun :exec
INSERT INTO ldap_sync_runs (
    id, tenant_id, source_id, actor_name, started_at, outcome
) VALUES ($1, $2, $3, $4, $5, 'RUNNING')
`

type StartLDAPSyncRunParams struct {
	ID        string
	TenantID  string
	SourceID  string
	ActorName string
	StartedAt time.Time
}

func (q *Queries) StartLDAPSyncRun(ctx context.Context, arg StartLDAPSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, startLDAPSyncRun,
		arg.ID,
		arg.TenantID,
		arg.SourceID,
		arg.ActorName,
		arg.StartedAt,
	)
	return err
}

const updateLDAPSource = `-- name: UpdateLDAPSource :exec
UPDATE ldap_sources
SET name = $1,
    host = $2,
    port = $3,
    encryption = $4,
    bind_dn = $5,
    base_dn = $6,
    user_filter = $7,
    attr_username = $8,
    attr_display_name = $9,
    attr_email = $10,
    attr_phone = $11,
    attr_external_id = $12,
    organization_id = $13,
    updated_at = $14
WHERE tenant_id = $15 AND id = $16
`

type UpdateLDAPSourceParams struct {
	Name            string
	Host            string
	Port            int32
	Encryption      string
	BindDn          string
	BaseDn          string
	UserFilter      string
	AttrUsername    string
	AttrDisplayName string
	AttrEmail       string
	AttrPhone       string
	AttrExternalID  string
	OrganizationID  *string
	UpdatedAt       time.Time
	TenantID        string
	ID              string
}

// The bind password is not in the SET list. It is rotated through its own
// statement so that an update which omits it leaves it alone — a form that
// cannot show the current value must not be able to blank it by submitting.
func (q *Queries) UpdateLDAPSource(ctx context.Context, arg UpdateLDAPSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateLDAPSource,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Encryption,
		arg.BindDn,
		arg.BaseDn,
		arg.UserFilter,
		arg.AttrUsername,
		arg.AttrDisplayName,
		arg.AttrEmail,
		arg.AttrPhone,
		arg.AttrExternalID,
		arg.OrganizationID,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateLDAPSourceBindPassword = `-- name: UpdateLDAPSourceBindPassword :exec
UPDATE ldap_sources
SET bind_password = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateLDAPSourceBindPasswordParams struct {
	BindPassword string
	UpdatedAt    time.Time
	TenantID     string
	ID           string
}

func (q *Queries) UpdateLDAPSourceBindPassword(ctx context.Context, arg UpdateLDAPSourceBindPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateLDAPSourceBindPassword,
		arg.BindPassword,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateLDAPSourceStatus = `-- name: UpdateLDAPSourceStatus :exec
UPDATE ldap_sources
SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateLDAPSourceStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) UpdateLDAPSourceStatus(ctx context.Context, arg UpdateLDAPSourceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLDAPSourceStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}
