// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type AuditLog struct {
	ID string
	// The tenant the event happened in. A sign-in naming a tenant that does not exist has no tenant to belong to and so is reported to the process log instead; see SECURITY.md.
	TenantID string
	Kind     string
	Action   string
	// Null when the actor could not be identified, such as a sign-in attempt against an unknown username.
	ActorID       *string
	ActorUsername string
	TargetType    string
	TargetID      string
	TargetName    string
	Result        string
	Detail        string
	Ip            string
	CreatedAt     time.Time
}

// Flat groupings of users. No hierarchy in this version.
type Organization struct {
	ID       string
	TenantID string
	Name     string
	// Stable identifier used by bulk import and downstream systems. Immutable once created.
	Code   string
	Remark string
	// DISABLED blocks new members but keeps existing ones.
	Status    string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Outstanding password-recovery requests. Rows are kept after use as part of the trail; expiry and used_at are what make a token unusable, not deletion.
type PasswordReset struct {
	ID        string
	TenantID  string
	UserID    string
	TokenHash string
	Channel   string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type SystemSetting struct {
	TenantID  string
	Key       string
	Value     string
	UpdatedAt time.Time
}

// Isolation boundary. Every other table is scoped to exactly one of these.
type Tenant struct {
	ID string
	// What a user types at sign-in to say which tenant they belong to. Immutable once created, because it appears in sign-in URLs and downstream configuration.
	Code string
	Name string
	// DISABLED refuses sign-in without deleting anything.
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           string
	TenantID     string
	Username     string
	DisplayName  string
	PasswordHash string
	// Doubles as a sign-in identifier and as the destination for password recovery. Unique within the tenant when set; empty means not bound.
	Phone string
	// Doubles as a sign-in identifier and as the destination for password recovery. Unique within the tenant when set; empty means not bound.
	Email          string
	Role           string
	Status         string
	OrganizationID *string
	// Bumped on logout, password change, and disable. A token carrying a stale value is rejected, which is how a stateless JWT is revoked immediately.
	TokenVersion int64
	// How the account came to exist, for the registration log.
	Source    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
