// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type AuditLog struct {
	ID string
	// The tenant the event happened in. A sign-in naming a tenant that does not exist has no tenant to belong to and so is reported to the process log instead; see SECURITY.md.
	TenantID string
	Kind     string
	Action   string
	// Null when the actor could not be identified, such as a sign-in attempt against an unknown username.
	ActorID       *string
	ActorUsername string
	TargetType    string
	TargetID      string
	TargetName    string
	Result        string
	Detail        string
	Ip            string
	CreatedAt     time.Time
}

type CasService struct {
	ID        string
	TenantID  string
	Name      string
	UrlPrefix string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	// Where a person opens this application. Not the URL prefix.
	LaunchUrl string
	// Picture for this application's portal tile. Absolute http(s) or a path on this server.
	LogoUri string
}

type CasTicket struct {
	ID         string
	TenantID   string
	TicketHash string
	Service    string
	Subject    string
	ConsumedAt *time.Time
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

type Group struct {
	ID          string
	TenantID    string
	DisplayName string
	Description string
	ExternalID  *string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupMember struct {
	TenantID string
	GroupID  string
	UserID   string
	AddedAt  time.Time
}

type LdapSource struct {
	ID              string
	TenantID        string
	Name            string
	Host            string
	Port            int32
	Encryption      string
	BindDn          string
	BindPassword    string
	BaseDn          string
	UserFilter      string
	AttrUsername    string
	AttrDisplayName string
	AttrEmail       string
	AttrPhone       string
	AttrExternalID  string
	OrganizationID  *string
	Status          string
	LastSyncedAt    *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type LdapSyncRun struct {
	ID               string
	TenantID         string
	SourceID         string
	ActorName        string
	StartedAt        time.Time
	FinishedAt       *time.Time
	Outcome          string
	CreatedCount     int32
	UpdatedCount     int32
	DeactivatedCount int32
	SkippedCount     int32
	ErrorCode        string
	Error            string
	SkippedDetail    string
}

type OauthAuthRequest struct {
	ID                  string
	TenantID            string
	ClientID            string
	Issuer              string
	Subject             *string
	RedirectUri         string
	ResponseType        string
	ResponseMode        string
	Scopes              []string
	Audience            []string
	State               string
	Nonce               string
	CodeChallenge       string
	CodeChallengeMethod string
	AuthTime            *time.Time
	Amr                 []string
	Done                bool
	CodeHash            *string
	CreatedAt           time.Time
	ExpiresAt           time.Time
}

type OauthClient struct {
	ID                     string
	TenantID               string
	ClientID               string
	Name                   string
	SecretHash             *string
	ApplicationType        string
	AuthMethod             string
	RedirectUris           []string
	PostLogoutRedirectUris []string
	GrantTypes             []string
	Scopes                 []string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	// Where a person opens this application. Not a redirect URI.
	LaunchUrl string
	// Picture for this application's portal tile. Absolute http(s) or a path on this server.
	LogoUri string
}

type OauthRefreshToken struct {
	ID         string
	TenantID   string
	ClientID   string
	Subject    string
	TokenHash  string
	Scopes     []string
	Audience   []string
	Amr        []string
	AuthTime   time.Time
	ReplacedBy *string
	UsedAt     *time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

type OauthSigningKey struct {
	ID        string
	TenantID  string
	Algorithm string
	// PKCS#8 PEM. Stored as the database stores everything else; protecting it is the deployment's job, the same as the password hashes beside it.
	PrivateKey string
	PublicKey  string
	Status     string
	CreatedAt  time.Time
	RetiredAt  *time.Time
}

// Groupings of users, arranged as a tree.
type Organization struct {
	ID       string
	TenantID string
	Name     string
	// Stable identifier used by bulk import and downstream systems. Immutable once created.
	Code   string
	Remark string
	// NULL for a root. Cycles and depth are enforced in the service layer: the foreign key alone cannot see a cycle, because every row in one is individually valid.
	ParentID *string
	// DISABLED blocks new members but keeps existing ones.
	Status    string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
	// Who is responsible for this organization. Grants nothing: this version has two fixed roles, and a field that quietly became a third would be the worst way to acquire one.
	ManagerID *string
}

type PasswordHistory struct {
	ID           string
	TenantID     string
	UserID       string
	PasswordHash string
	CreatedAt    time.Time
}

// Outstanding password-recovery requests. Rows are kept after use as part of the trail; expiry and used_at are what make a token unusable, not deletion.
type PasswordReset struct {
	ID        string
	TenantID  string
	UserID    string
	TokenHash string
	Channel   string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

// Outstanding address-verification requests from self-registration. Rows survive use as part of the trail; expiry and used_at are what make a token unusable, not deletion.
type RegistrationVerification struct {
	ID        string
	TenantID  string
	UserID    string
	TokenHash string
	Channel   string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type SamlAuthRequest struct {
	ID         string
	TenantID   string
	Issuer     string
	RequestXml string
	RelayState string
	SpEntityID string
	Subject    *string
	Done       bool
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

type SamlServiceProvider struct {
	ID          string
	TenantID    string
	EntityID    string
	Name        string
	MetadataXml string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	// Where a person opens this application. Not an assertion consumer service.
	LaunchUrl string
	// Picture for this application's portal tile. Absolute http(s) or a path on this server.
	LogoUri string
}

type SamlSigningKey struct {
	ID          string
	TenantID    string
	PrivateKey  string
	Certificate string
	Status      string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	RetiredAt   *time.Time
}

type ScimCredential struct {
	ID          string
	TenantID    string
	Name        string
	TokenHash   string
	TokenPrefix string
	Status      string
	LastUsedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID        string
	TenantID  string
	UserID    string
	Ip        string
	UserAgent string
	CreatedAt time.Time
	// Updated lazily rather than on every request: a write per request would make every read a write, and minute-level accuracy is all a session list needs.
	LastSeenAt time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
}

type SystemSetting struct {
	TenantID  string
	Key       string
	Value     string
	UpdatedAt time.Time
}

// Isolation boundary. Every other table is scoped to exactly one of these.
type Tenant struct {
	ID string
	// What a user types at sign-in to say which tenant they belong to. Immutable once created, because it appears in sign-in URLs and downstream configuration.
	Code string
	Name string
	// DISABLED refuses sign-in without deleting anything.
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           string
	TenantID     string
	Username     string
	DisplayName  string
	PasswordHash string
	// Doubles as a sign-in identifier and as the destination for password recovery. Unique within the tenant when set; empty means not bound.
	Phone string
	// Doubles as a sign-in identifier and as the destination for password recovery. Unique within the tenant when set; empty means not bound.
	Email          string
	Role           string
	Status         string
	OrganizationID *string
	// Bumped on logout, password change, and disable. A token carrying a stale value is rejected, which is how a stateless JWT is revoked immediately.
	TokenVersion int64
	// How the account came to exist, for the registration log.
	Source     string
	ExternalID *string
	// Consecutive failures within the counting window. Reset by a successful sign-in, by a completed password recovery, and by an administrator unlocking the account.
	FailedLoginAttempts int32
	LastFailedLoginAt   *time.Time
	// Set when the threshold is reached; expires on its own. Further failures while locked do not extend it, or locking somebody out would be a denial of service anyone could perform.
	LockedUntil *time.Time
	// When the current password was set. NULL means never changed since the account was created, which an expiry policy treats as due.
	PasswordChangedAt *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	// The directory that owns this account, or null when Portico does.
	LdapSourceID *string
	// When the account holder closed this account. Null for every other reason it might be disabled.
	ClosedAt *time.Time
	// When a self-registered account's contact address was accepted — either proven by a link, or accepted at registration because the tenant did not require proof. Null means the account still has to prove it. Only consulted for source = REGISTRATION.
	VerifiedAt        *time.Time
	NameFormatted     string
	FamilyName        string
	GivenName         string
	MiddleName        string
	HonorificPrefix   string
	HonorificSuffix   string
	NickName          string
	ProfileUrl        string
	PhotoUrl          string
	Title             string
	UserType          string
	PreferredLanguage string
	Locale            string
	Timezone          string
	AddressFormatted  string
	StreetAddress     string
	Locality          string
	Region            string
	PostalCode        string
	Country           string
	EmployeeNumber    string
	CostCenter        string
	// Free text as a directory sends it. Distinct from organization_id, which is this tenant's own tree; keeping both loses nothing and lets an operator place somebody later.
	Department string
	// Who this person reports to. Not checked for cycles: one is a data-quality problem in the source system rather than something this schema can prevent.
	ManagerID *string
}

// Additional organizations a person is attached to. Advisory: grants nothing, synchronizes nowhere, and does not change users.organization_id, which remains the one authoritative membership.
type UserOrganizationAttachment struct {
	TenantID       string
	UserID         string
	OrganizationID string
	CreatedAt      time.Time
}

type WebhookDelivery struct {
	ID             string
	TenantID       string
	SubscriptionID string
	EventType      string
	Payload        string
	Status         string
	Attempts       int32
	LastError      string
	LastStatus     sql.NullInt32
	NextAttemptAt  *time.Time
	CreatedAt      time.Time
	DeliveredAt    *time.Time
}

type WebhookSubscription struct {
	ID        string
	TenantID  string
	Name      string
	Url       string
	Secret    string
	Events    string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
