// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	dbtime "github.com/paraview/portico/internal/store/dbtime"
)

type AuditLog struct {
	ID            string
	Kind          string
	Action        string
	ActorID       *string
	ActorUsername string
	TargetType    string
	TargetID      string
	TargetName    string
	Result        string
	Detail        string
	Ip            string
	CreatedAt     dbtime.Time
}

type Organization struct {
	ID        string
	Name      string
	Code      string
	Remark    string
	Status    string
	SortOrder int64
	CreatedAt dbtime.Time
	UpdatedAt dbtime.Time
}

type SystemSetting struct {
	Key       string
	Value     string
	UpdatedAt dbtime.Time
}

type User struct {
	ID             string
	Username       string
	DisplayName    string
	PasswordHash   string
	Phone          string
	Email          string
	Role           string
	Status         string
	OrganizationID *string
	TokenVersion   int64
	Source         string
	CreatedAt      dbtime.Time
	UpdatedAt      dbtime.Time
}
