// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO oauth_refresh_tokens (
    id, tenant_id, client_id, subject, token_hash,
    scopes, audience, amr, auth_time, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateRefreshTokenParams struct {
	ID        string
	TenantID  string
	ClientID  string
	Subject   string
	TokenHash string
	Scopes    []string
	Audience  []string
	Amr       []string
	AuthTime  time.Time
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.TenantID,
		arg.ClientID,
		arg.Subject,
		arg.TokenHash,
		pq.Array(arg.Scopes),
		pq.Array(arg.Audience),
		pq.Array(arg.Amr),
		arg.AuthTime,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, tenant_id, client_id, subject, token_hash, scopes, audience, amr, auth_time, replaced_by, used_at, revoked_at, created_at, expires_at FROM oauth_refresh_tokens
WHERE tenant_id = $1 AND token_hash = $2
LIMIT 1
`

type GetRefreshTokenParams struct {
	TenantID  string
	TokenHash string
}

// Returns the row whatever its state, because the caller has to be able to
// tell "expired" from "already spent" — a spent token being presented means
// a copy leaked, and that calls for revoking the whole chain rather than
// simply failing the call.
func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (OauthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, arg.TenantID, arg.TokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Subject,
		&i.TokenHash,
		pq.Array(&i.Scopes),
		pq.Array(&i.Audience),
		pq.Array(&i.Amr),
		&i.AuthTime,
		&i.ReplacedBy,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE oauth_refresh_tokens
SET revoked_at = $1
WHERE tenant_id = $2 AND subject = $3 AND revoked_at IS NULL
`

type RevokeAllRefreshTokensForUserParams struct {
	RevokedAt *time.Time
	TenantID  string
	Subject   string
}

// Every relying party at once. Signing out of Portico, changing a password,
// or being disabled has to reach the tokens other systems are holding, or
// "sessions revoke immediately" stops being true the moment federation is
// switched on.
func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, arg RevokeAllRefreshTokensForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllRefreshTokensForUser, arg.RevokedAt, arg.TenantID, arg.Subject)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE oauth_refresh_tokens
SET revoked_at = $1
WHERE tenant_id = $2 AND id = $3 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	RevokedAt *time.Time
	TenantID  string
	ID        string
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.RevokedAt, arg.TenantID, arg.ID)
	return err
}

const revokeRefreshTokenChain = `-- name: RevokeRefreshTokenChain :exec
WITH RECURSIVE chain AS (
    SELECT r.id, r.replaced_by
    FROM oauth_refresh_tokens r
    WHERE r.tenant_id = $2 AND r.id = $3
    UNION ALL
    SELECT t.id, t.replaced_by
    FROM oauth_refresh_tokens t
    JOIN chain c ON t.id = c.replaced_by
    WHERE t.tenant_id = $2
)
UPDATE oauth_refresh_tokens o
SET revoked_at = $1
WHERE o.tenant_id = $2 AND o.id IN (SELECT id FROM chain) AND o.revoked_at IS NULL
`

type RevokeRefreshTokenChainParams struct {
	RevokedAt *time.Time
	TenantID  string
	ID        string
}

// Revokes every token descended from one, following replaced_by. Used when a
// spent token is presented: which link of the chain leaked is unknown, so
// the whole chain goes.
func (q *Queries) RevokeRefreshTokenChain(ctx context.Context, arg RevokeRefreshTokenChainParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenChain, arg.RevokedAt, arg.TenantID, arg.ID)
	return err
}

const revokeRefreshTokensForSession = `-- name: RevokeRefreshTokensForSession :exec
UPDATE oauth_refresh_tokens
SET revoked_at = $1
WHERE tenant_id = $2 AND subject = $3 AND client_id = $4 AND revoked_at IS NULL
`

type RevokeRefreshTokensForSessionParams struct {
	RevokedAt *time.Time
	TenantID  string
	Subject   string
	ClientID  string
}

// Ends a person's session with one relying party, which is what RP-initiated
// logout and TerminateSession mean.
func (q *Queries) RevokeRefreshTokensForSession(ctx context.Context, arg RevokeRefreshTokensForSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokensForSession,
		arg.RevokedAt,
		arg.TenantID,
		arg.Subject,
		arg.ClientID,
	)
	return err
}

const spendRefreshToken = `-- name: SpendRefreshToken :exec
UPDATE oauth_refresh_tokens
SET used_at = $1, replaced_by = $2
WHERE tenant_id = $3 AND id = $4
`

type SpendRefreshTokenParams struct {
	UsedAt     *time.Time
	ReplacedBy *string
	TenantID   string
	ID         string
}

func (q *Queries) SpendRefreshToken(ctx context.Context, arg SpendRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, spendRefreshToken,
		arg.UsedAt,
		arg.ReplacedBy,
		arg.TenantID,
		arg.ID,
	)
	return err
}
