// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_keys.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSigningKey = `-- name: CreateSigningKey :exec
INSERT INTO oauth_signing_keys (
    id, tenant_id, algorithm, private_key, public_key, status, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSigningKeyParams struct {
	ID         string
	TenantID   string
	Algorithm  string
	PrivateKey string
	PublicKey  string
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error {
	_, err := q.db.ExecContext(ctx, createSigningKey,
		arg.ID,
		arg.TenantID,
		arg.Algorithm,
		arg.PrivateKey,
		arg.PublicKey,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSigningKeys = `-- name: DeleteExpiredSigningKeys :exec
DELETE FROM oauth_signing_keys
WHERE tenant_id = $1 AND status = 'RETIRED' AND retired_at < $2
`

type DeleteExpiredSigningKeysParams struct {
	TenantID  string
	RetiredAt *time.Time
}

// Retired long enough that nothing it signed can still be valid.
func (q *Queries) DeleteExpiredSigningKeys(ctx context.Context, arg DeleteExpiredSigningKeysParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSigningKeys, arg.TenantID, arg.RetiredAt)
	return err
}

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT id, tenant_id, algorithm, private_key, public_key, status, created_at, retired_at FROM oauth_signing_keys
WHERE tenant_id = $1 AND status = 'ACTIVE'
ORDER BY created_at DESC
LIMIT 1
`

// The key new tokens are signed with. There is exactly one; rotation makes a
// new one active and retires the old, rather than leaving two to choose from.
func (q *Queries) GetActiveSigningKey(ctx context.Context, tenantID string) (OauthSigningKey, error) {
	row := q.db.QueryRowContext(ctx, getActiveSigningKey, tenantID)
	var i OauthSigningKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Algorithm,
		&i.PrivateKey,
		&i.PublicKey,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const listPublishedSigningKeys = `-- name: ListPublishedSigningKeys :many
SELECT id, tenant_id, algorithm, private_key, public_key, status, created_at, retired_at FROM oauth_signing_keys
WHERE tenant_id = $1
  AND (retired_at IS NULL OR retired_at > $2)
ORDER BY created_at DESC
`

type ListPublishedSigningKeysParams struct {
	TenantID  string
	RetiredAt *time.Time
}

// Everything the JWKS advertises: the active key and any retired key whose
// tokens may still be in flight. A relying party that fetched the key set
// before a rotation must still be able to verify what it holds.
//
// The cutoff is applied here rather than left to whatever prunes the rows,
// so what the key set offers does not depend on a background job having run.
// Without it a tenant that rotated once and never again advertised the key
// it rotated away from for the life of the deployment — and rotating is
// usually done precisely because that key should stop being trusted.
func (q *Queries) ListPublishedSigningKeys(ctx context.Context, arg ListPublishedSigningKeysParams) ([]OauthSigningKey, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedSigningKeys, arg.TenantID, arg.RetiredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthSigningKey{}
	for rows.Next() {
		var i OauthSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Algorithm,
			&i.PrivateKey,
			&i.PublicKey,
			&i.Status,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireSigningKeys = `-- name: RetireSigningKeys :exec
UPDATE oauth_signing_keys
SET status = 'RETIRED', retired_at = $1
WHERE tenant_id = $2 AND status = 'ACTIVE'
`

type RetireSigningKeysParams struct {
	RetiredAt *time.Time
	TenantID  string
}

func (q *Queries) RetireSigningKeys(ctx context.Context, arg RetireSigningKeysParams) error {
	_, err := q.db.ExecContext(ctx, retireSigningKeys, arg.RetiredAt, arg.TenantID)
	return err
}
