// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_clients.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createOAuthClient = `-- name: CreateOAuthClient :exec
INSERT INTO oauth_clients (
    id, tenant_id, client_id, name, secret_hash,
    application_type, auth_method,
    redirect_uris, post_logout_redirect_uris, grant_types, scopes,
    status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateOAuthClientParams struct {
	ID                     string
	TenantID               string
	ClientID               string
	Name                   string
	SecretHash             *string
	ApplicationType        string
	AuthMethod             string
	RedirectUris           []string
	PostLogoutRedirectUris []string
	GrantTypes             []string
	Scopes                 []string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthClient,
		arg.ID,
		arg.TenantID,
		arg.ClientID,
		arg.Name,
		arg.SecretHash,
		arg.ApplicationType,
		arg.AuthMethod,
		pq.Array(arg.RedirectUris),
		pq.Array(arg.PostLogoutRedirectUris),
		pq.Array(arg.GrantTypes),
		pq.Array(arg.Scopes),
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, tenant_id, client_id, name, secret_hash, application_type, auth_method, redirect_uris, post_logout_redirect_uris, grant_types, scopes, status, created_at, updated_at FROM oauth_clients WHERE tenant_id = $1 AND client_id = $2 LIMIT 1
`

type GetOAuthClientParams struct {
	TenantID string
	ClientID string
}

func (q *Queries) GetOAuthClient(ctx context.Context, arg GetOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClient, arg.TenantID, arg.ClientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.SecretHash,
		&i.ApplicationType,
		&i.AuthMethod,
		pq.Array(&i.RedirectUris),
		pq.Array(&i.PostLogoutRedirectUris),
		pq.Array(&i.GrantTypes),
		pq.Array(&i.Scopes),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, tenant_id, client_id, name, secret_hash, application_type, auth_method, redirect_uris, post_logout_redirect_uris, grant_types, scopes, status, created_at, updated_at FROM oauth_clients WHERE tenant_id = $1 ORDER BY created_at
`

func (q *Queries) ListOAuthClients(ctx context.Context, tenantID string) ([]OauthClient, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthClients, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClient{}
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.Name,
			&i.SecretHash,
			&i.ApplicationType,
			&i.AuthMethod,
			pq.Array(&i.RedirectUris),
			pq.Array(&i.PostLogoutRedirectUris),
			pq.Array(&i.GrantTypes),
			pq.Array(&i.Scopes),
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthClientStatus = `-- name: UpdateOAuthClientStatus :exec
UPDATE oauth_clients
SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND client_id = $4
`

type UpdateOAuthClientStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	ClientID  string
}

func (q *Queries) UpdateOAuthClientStatus(ctx context.Context, arg UpdateOAuthClientStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOAuthClientStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ClientID,
	)
	return err
}
