// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_requests.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const completeAuthRequest = `-- name: CompleteAuthRequest :exec
UPDATE oauth_auth_requests
SET subject = $1, auth_time = $2, amr = $3, done = TRUE
WHERE tenant_id = $4 AND id = $5
`

type CompleteAuthRequestParams struct {
	Subject  *string
	AuthTime *time.Time
	Amr      []string
	TenantID string
	ID       string
}

// Records who signed in. Until this runs the request has no subject and
// cannot produce a token.
func (q *Queries) CompleteAuthRequest(ctx context.Context, arg CompleteAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, completeAuthRequest,
		arg.Subject,
		arg.AuthTime,
		pq.Array(arg.Amr),
		arg.TenantID,
		arg.ID,
	)
	return err
}

const createAuthRequest = `-- name: CreateAuthRequest :exec
INSERT INTO oauth_auth_requests (
    id, tenant_id, client_id, redirect_uri, response_type, response_mode,
    scopes, audience, state, nonce, code_challenge, code_challenge_method,
    created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateAuthRequestParams struct {
	ID                  string
	TenantID            string
	ClientID            string
	RedirectUri         string
	ResponseType        string
	ResponseMode        string
	Scopes              []string
	Audience            []string
	State               string
	Nonce               string
	CodeChallenge       string
	CodeChallengeMethod string
	CreatedAt           time.Time
	ExpiresAt           time.Time
}

func (q *Queries) CreateAuthRequest(ctx context.Context, arg CreateAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, createAuthRequest,
		arg.ID,
		arg.TenantID,
		arg.ClientID,
		arg.RedirectUri,
		arg.ResponseType,
		arg.ResponseMode,
		pq.Array(arg.Scopes),
		pq.Array(arg.Audience),
		arg.State,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAuthRequest = `-- name: DeleteAuthRequest :exec
DELETE FROM oauth_auth_requests WHERE tenant_id = $1 AND id = $2
`

type DeleteAuthRequestParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteAuthRequest(ctx context.Context, arg DeleteAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, deleteAuthRequest, arg.TenantID, arg.ID)
	return err
}

const deleteExpiredAuthRequests = `-- name: DeleteExpiredAuthRequests :exec
DELETE FROM oauth_auth_requests WHERE tenant_id = $1 AND expires_at < $2
`

type DeleteExpiredAuthRequestsParams struct {
	TenantID  string
	ExpiresAt time.Time
}

func (q *Queries) DeleteExpiredAuthRequests(ctx context.Context, arg DeleteExpiredAuthRequestsParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthRequests, arg.TenantID, arg.ExpiresAt)
	return err
}

const getAuthRequest = `-- name: GetAuthRequest :one
SELECT id, tenant_id, client_id, subject, redirect_uri, response_type, response_mode, scopes, audience, state, nonce, code_challenge, code_challenge_method, auth_time, amr, done, code_hash, created_at, expires_at FROM oauth_auth_requests
WHERE tenant_id = $1 AND id = $2 AND expires_at > $3
LIMIT 1
`

type GetAuthRequestParams struct {
	TenantID  string
	ID        string
	ExpiresAt time.Time
}

func (q *Queries) GetAuthRequest(ctx context.Context, arg GetAuthRequestParams) (OauthAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequest, arg.TenantID, arg.ID, arg.ExpiresAt)
	var i OauthAuthRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Subject,
		&i.RedirectUri,
		&i.ResponseType,
		&i.ResponseMode,
		pq.Array(&i.Scopes),
		pq.Array(&i.Audience),
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthTime,
		pq.Array(&i.Amr),
		&i.Done,
		&i.CodeHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAuthRequestByCode = `-- name: GetAuthRequestByCode :one
SELECT id, tenant_id, client_id, subject, redirect_uri, response_type, response_mode, scopes, audience, state, nonce, code_challenge, code_challenge_method, auth_time, amr, done, code_hash, created_at, expires_at FROM oauth_auth_requests
WHERE tenant_id = $1 AND code_hash = $2 AND done = TRUE AND expires_at > $3
LIMIT 1
`

type GetAuthRequestByCodeParams struct {
	TenantID  string
	CodeHash  *string
	ExpiresAt time.Time
}

// Only an unexpired, completed request can be exchanged. Both conditions are
// in the query so a caller cannot hold a row it forgot to check.
func (q *Queries) GetAuthRequestByCode(ctx context.Context, arg GetAuthRequestByCodeParams) (OauthAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequestByCode, arg.TenantID, arg.CodeHash, arg.ExpiresAt)
	var i OauthAuthRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Subject,
		&i.RedirectUri,
		&i.ResponseType,
		&i.ResponseMode,
		pq.Array(&i.Scopes),
		pq.Array(&i.Audience),
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthTime,
		pq.Array(&i.Amr),
		&i.Done,
		&i.CodeHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const saveAuthCode = `-- name: SaveAuthCode :exec
UPDATE oauth_auth_requests
SET code_hash = $1
WHERE tenant_id = $2 AND id = $3
`

type SaveAuthCodeParams struct {
	CodeHash *string
	TenantID string
	ID       string
}

func (q *Queries) SaveAuthCode(ctx context.Context, arg SaveAuthCodeParams) error {
	_, err := q.db.ExecContext(ctx, saveAuthCode, arg.CodeHash, arg.TenantID, arg.ID)
	return err
}
