// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const assignOrganizationAdministrator = `-- name: AssignOrganizationAdministrator :exec
INSERT INTO organization_administrators (
    tenant_id, organization_id, user_id, scope, granted_by, granted_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type AssignOrganizationAdministratorParams struct {
	TenantID       string
	OrganizationID string
	UserID         string
	Scope          string
	GrantedBy      string
	GrantedAt      time.Time
}

// Records who would administer an organization once delegated
// administration exists. It grants nothing today; see the migration.
func (q *Queries) AssignOrganizationAdministrator(ctx context.Context, arg AssignOrganizationAdministratorParams) error {
	_, err := q.db.ExecContext(ctx, assignOrganizationAdministrator,
		arg.TenantID,
		arg.OrganizationID,
		arg.UserID,
		arg.Scope,
		arg.GrantedBy,
		arg.GrantedAt,
	)
	return err
}

const attachUserToOrganization = `-- name: AttachUserToOrganization :exec
INSERT INTO user_organization_attachments (tenant_id, user_id, organization_id, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, user_id, organization_id) DO NOTHING
`

type AttachUserToOrganizationParams struct {
	TenantID       string
	UserID         string
	OrganizationID string
	CreatedAt      time.Time
}

func (q *Queries) AttachUserToOrganization(ctx context.Context, arg AttachUserToOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, attachUserToOrganization,
		arg.TenantID,
		arg.UserID,
		arg.OrganizationID,
		arg.CreatedAt,
	)
	return err
}

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (
    id, tenant_id, name, code, remark, parent_id, status, sort_order,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateOrganizationParams struct {
	ID        string
	TenantID  string
	Name      string
	Code      string
	Remark    string
	ParentID  *string
	Status    string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.Remark,
		arg.ParentID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const detachUserFromOrganization = `-- name: DetachUserFromOrganization :exec
DELETE FROM user_organization_attachments
WHERE tenant_id = $1 AND user_id = $2 AND organization_id = $3
`

type DetachUserFromOrganizationParams struct {
	TenantID       string
	UserID         string
	OrganizationID string
}

func (q *Queries) DetachUserFromOrganization(ctx context.Context, arg DetachUserFromOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, detachUserFromOrganization, arg.TenantID, arg.UserID, arg.OrganizationID)
	return err
}

const getOrganizationAdministrator = `-- name: GetOrganizationAdministrator :one
SELECT tenant_id, organization_id, user_id, scope, granted_by, granted_at FROM organization_administrators
WHERE tenant_id = $1 AND organization_id = $2 AND user_id = $3
`

type GetOrganizationAdministratorParams struct {
	TenantID       string
	OrganizationID string
	UserID         string
}

func (q *Queries) GetOrganizationAdministrator(ctx context.Context, arg GetOrganizationAdministratorParams) (OrganizationAdministrator, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationAdministrator, arg.TenantID, arg.OrganizationID, arg.UserID)
	var i OrganizationAdministrator
	err := row.Scan(
		&i.TenantID,
		&i.OrganizationID,
		&i.UserID,
		&i.Scope,
		&i.GrantedBy,
		&i.GrantedAt,
	)
	return i, err
}

const getOrganizationByCode = `-- name: GetOrganizationByCode :one
SELECT id, tenant_id, name, code, remark, parent_id, status, sort_order, created_at, updated_at, manager_id FROM organizations WHERE tenant_id = $1 AND code = $2 LIMIT 1
`

type GetOrganizationByCodeParams struct {
	TenantID string
	Code     string
}

func (q *Queries) GetOrganizationByCode(ctx context.Context, arg GetOrganizationByCodeParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByCode, arg.TenantID, arg.Code)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Remark,
		&i.ParentID,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManagerID,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, tenant_id, name, code, remark, parent_id, status, sort_order, created_at, updated_at, manager_id FROM organizations WHERE tenant_id = $1 AND id = $2 LIMIT 1
`

type GetOrganizationByIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetOrganizationByID(ctx context.Context, arg GetOrganizationByIDParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByID, arg.TenantID, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Remark,
		&i.ParentID,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManagerID,
	)
	return i, err
}

const listActiveOrganizations = `-- name: ListActiveOrganizations :many
SELECT id, tenant_id, name, code, remark, parent_id, status, sort_order, created_at, updated_at, manager_id FROM organizations
WHERE tenant_id = $1 AND status = 'ACTIVE'
ORDER BY sort_order, created_at
`

func (q *Queries) ListActiveOrganizations(ctx context.Context, tenantID string) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listActiveOrganizations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Remark,
			&i.ParentID,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationAdministrators = `-- name: ListOrganizationAdministrators :many
SELECT u.id, u.tenant_id, u.username, u.display_name, u.password_hash, u.phone, u.email, u.role, u.status, u.organization_id, u.token_version, u.source, u.external_id, u.failed_login_attempts, u.last_failed_login_at, u.locked_until, u.password_changed_at, u.created_at, u.updated_at, u.ldap_source_id, u.closed_at, u.verified_at, u.name_formatted, u.family_name, u.given_name, u.middle_name, u.honorific_prefix, u.honorific_suffix, u.nick_name, u.profile_url, u.photo_url, u.title, u.user_type, u.preferred_language, u.locale, u.timezone, u.address_formatted, u.street_address, u.locality, u.region, u.postal_code, u.country, u.employee_number, u.cost_center, u.department, u.manager_id, u.must_change_password, a.scope, a.granted_by, a.granted_at
FROM organization_administrators a
JOIN users u ON u.tenant_id = a.tenant_id AND u.id = a.user_id
WHERE a.tenant_id = $1 AND a.organization_id = $2
ORDER BY u.display_name
`

type ListOrganizationAdministratorsParams struct {
	TenantID       string
	OrganizationID string
}

type ListOrganizationAdministratorsRow struct {
	User      User
	Scope     string
	GrantedBy string
	GrantedAt time.Time
}

// The account with the assignment, so a caller can show a name and whether
// the person is still usable. Disabled accounts are listed rather than
// filtered: an assignment that disappeared when somebody was suspended would
// come back on its own when they were reinstated, and nobody would have
// decided either.
func (q *Queries) ListOrganizationAdministrators(ctx context.Context, arg ListOrganizationAdministratorsParams) ([]ListOrganizationAdministratorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationAdministrators, arg.TenantID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationAdministratorsRow{}
	for rows.Next() {
		var i ListOrganizationAdministratorsRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.TenantID,
			&i.User.Username,
			&i.User.DisplayName,
			&i.User.PasswordHash,
			&i.User.Phone,
			&i.User.Email,
			&i.User.Role,
			&i.User.Status,
			&i.User.OrganizationID,
			&i.User.TokenVersion,
			&i.User.Source,
			&i.User.ExternalID,
			&i.User.FailedLoginAttempts,
			&i.User.LastFailedLoginAt,
			&i.User.LockedUntil,
			&i.User.PasswordChangedAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LdapSourceID,
			&i.User.ClosedAt,
			&i.User.VerifiedAt,
			&i.User.NameFormatted,
			&i.User.FamilyName,
			&i.User.GivenName,
			&i.User.MiddleName,
			&i.User.HonorificPrefix,
			&i.User.HonorificSuffix,
			&i.User.NickName,
			&i.User.ProfileUrl,
			&i.User.PhotoUrl,
			&i.User.Title,
			&i.User.UserType,
			&i.User.PreferredLanguage,
			&i.User.Locale,
			&i.User.Timezone,
			&i.User.AddressFormatted,
			&i.User.StreetAddress,
			&i.User.Locality,
			&i.User.Region,
			&i.User.PostalCode,
			&i.User.Country,
			&i.User.EmployeeNumber,
			&i.User.CostCenter,
			&i.User.Department,
			&i.User.ManagerID,
			&i.User.MustChangePassword,
			&i.Scope,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationAttachedUsers = `-- name: ListOrganizationAttachedUsers :many
SELECT u.id, u.tenant_id, u.username, u.display_name, u.password_hash, u.phone, u.email, u.role, u.status, u.organization_id, u.token_version, u.source, u.external_id, u.failed_login_attempts, u.last_failed_login_at, u.locked_until, u.password_changed_at, u.created_at, u.updated_at, u.ldap_source_id, u.closed_at, u.verified_at, u.name_formatted, u.family_name, u.given_name, u.middle_name, u.honorific_prefix, u.honorific_suffix, u.nick_name, u.profile_url, u.photo_url, u.title, u.user_type, u.preferred_language, u.locale, u.timezone, u.address_formatted, u.street_address, u.locality, u.region, u.postal_code, u.country, u.employee_number, u.cost_center, u.department, u.manager_id, u.must_change_password FROM users u
JOIN user_organization_attachments a
  ON a.tenant_id = u.tenant_id AND a.user_id = u.id
WHERE a.tenant_id = $1 AND a.organization_id = $2
ORDER BY u.display_name
`

type ListOrganizationAttachedUsersParams struct {
	TenantID       string
	OrganizationID string
}

func (q *Queries) ListOrganizationAttachedUsers(ctx context.Context, arg ListOrganizationAttachedUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationAttachedUsers, arg.TenantID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Phone,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.OrganizationID,
			&i.TokenVersion,
			&i.Source,
			&i.ExternalID,
			&i.FailedLoginAttempts,
			&i.LastFailedLoginAt,
			&i.LockedUntil,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LdapSourceID,
			&i.ClosedAt,
			&i.VerifiedAt,
			&i.NameFormatted,
			&i.FamilyName,
			&i.GivenName,
			&i.MiddleName,
			&i.HonorificPrefix,
			&i.HonorificSuffix,
			&i.NickName,
			&i.ProfileUrl,
			&i.PhotoUrl,
			&i.Title,
			&i.UserType,
			&i.PreferredLanguage,
			&i.Locale,
			&i.Timezone,
			&i.AddressFormatted,
			&i.StreetAddress,
			&i.Locality,
			&i.Region,
			&i.PostalCode,
			&i.Country,
			&i.EmployeeNumber,
			&i.CostCenter,
			&i.Department,
			&i.ManagerID,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, tenant_id, name, code, remark, parent_id, status, sort_order, created_at, updated_at, manager_id FROM organizations WHERE tenant_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListOrganizations(ctx context.Context, tenantID string) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Remark,
			&i.ParentID,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsAdministeredBy = `-- name: ListOrganizationsAdministeredBy :many
SELECT o.id, o.tenant_id, o.name, o.code, o.remark, o.parent_id, o.status, o.sort_order, o.created_at, o.updated_at, o.manager_id, a.scope, a.granted_at
FROM organization_administrators a
JOIN organizations o ON o.tenant_id = a.tenant_id AND o.id = a.organization_id
WHERE a.tenant_id = $1 AND a.user_id = $2
ORDER BY o.sort_order, o.created_at
`

type ListOrganizationsAdministeredByParams struct {
	TenantID string
	UserID   string
}

type ListOrganizationsAdministeredByRow struct {
	Organization Organization
	Scope        string
	GrantedAt    time.Time
}

// The query delegated administration will make on every request. Nothing
// consumes it for a decision yet; the console shows it on an account.
func (q *Queries) ListOrganizationsAdministeredBy(ctx context.Context, arg ListOrganizationsAdministeredByParams) ([]ListOrganizationsAdministeredByRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsAdministeredBy, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsAdministeredByRow{}
	for rows.Next() {
		var i ListOrganizationsAdministeredByRow
		if err := rows.Scan(
			&i.Organization.ID,
			&i.Organization.TenantID,
			&i.Organization.Name,
			&i.Organization.Code,
			&i.Organization.Remark,
			&i.Organization.ParentID,
			&i.Organization.Status,
			&i.Organization.SortOrder,
			&i.Organization.CreatedAt,
			&i.Organization.UpdatedAt,
			&i.Organization.ManagerID,
			&i.Scope,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByIDs = `-- name: ListOrganizationsByIDs :many
SELECT id, tenant_id, name, code, remark, parent_id, status, sort_order, created_at, updated_at, manager_id FROM organizations WHERE tenant_id = $1 AND id = ANY($2::text[])
`

type ListOrganizationsByIDsParams struct {
	TenantID string
	Column2  []string
}

func (q *Queries) ListOrganizationsByIDs(ctx context.Context, arg ListOrganizationsByIDsParams) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsByIDs, arg.TenantID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Remark,
			&i.ParentID,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizationAttachments = `-- name: ListUserOrganizationAttachments :many
SELECT o.id, o.tenant_id, o.name, o.code, o.remark, o.parent_id, o.status, o.sort_order, o.created_at, o.updated_at, o.manager_id FROM organizations o
JOIN user_organization_attachments a
  ON a.tenant_id = o.tenant_id AND a.organization_id = o.id
WHERE a.tenant_id = $1 AND a.user_id = $2
ORDER BY o.sort_order, o.created_at
`

type ListUserOrganizationAttachmentsParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) ListUserOrganizationAttachments(ctx context.Context, arg ListUserOrganizationAttachmentsParams) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listUserOrganizationAttachments, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Remark,
			&i.ParentID,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOrganizationAdministrator = `-- name: RevokeOrganizationAdministrator :exec
DELETE FROM organization_administrators
WHERE tenant_id = $1 AND organization_id = $2 AND user_id = $3
`

type RevokeOrganizationAdministratorParams struct {
	TenantID       string
	OrganizationID string
	UserID         string
}

func (q *Queries) RevokeOrganizationAdministrator(ctx context.Context, arg RevokeOrganizationAdministratorParams) error {
	_, err := q.db.ExecContext(ctx, revokeOrganizationAdministrator, arg.TenantID, arg.OrganizationID, arg.UserID)
	return err
}

const setOrganizationManager = `-- name: SetOrganizationManager :exec
UPDATE organizations
SET manager_id = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type SetOrganizationManagerParams struct {
	ManagerID *string
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) SetOrganizationManager(ctx context.Context, arg SetOrganizationManagerParams) error {
	_, err := q.db.ExecContext(ctx, setOrganizationManager,
		arg.ManagerID,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = $1,
    remark = $2,
    parent_id = $3,
    sort_order = $4,
    updated_at = $5
WHERE tenant_id = $6 AND id = $7
`

type UpdateOrganizationParams struct {
	Name      string
	Remark    string
	ParentID  *string
	SortOrder int64
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganization,
		arg.Name,
		arg.Remark,
		arg.ParentID,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :exec
UPDATE organizations
SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateOrganizationStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganizationStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}
