// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlcgen

import (
	"context"
	"strings"

	dbtime "github.com/paraview/keylite/internal/store/dbtime"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (
    id, name, code, remark, status, sort_order, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrganizationParams struct {
	ID        string
	Name      string
	Code      string
	Remark    string
	Status    string
	SortOrder int64
	CreatedAt dbtime.Time
	UpdatedAt dbtime.Time
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Remark,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOrganizationByCode = `-- name: GetOrganizationByCode :one
SELECT id, name, code, remark, status, sort_order, created_at, updated_at FROM organizations WHERE code = ? LIMIT 1
`

func (q *Queries) GetOrganizationByCode(ctx context.Context, code string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByCode, code)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Remark,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, code, remark, status, sort_order, created_at, updated_at FROM organizations WHERE id = ? LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Remark,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOrganizations = `-- name: ListActiveOrganizations :many
SELECT id, name, code, remark, status, sort_order, created_at, updated_at FROM organizations WHERE status = 'ACTIVE' ORDER BY sort_order, created_at
`

func (q *Queries) ListActiveOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listActiveOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Remark,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, code, remark, status, sort_order, created_at, updated_at FROM organizations ORDER BY sort_order, created_at
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Remark,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByIDs = `-- name: ListOrganizationsByIDs :many
SELECT id, name, code, remark, status, sort_order, created_at, updated_at FROM organizations WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListOrganizationsByIDs(ctx context.Context, ids []string) ([]Organization, error) {
	query := listOrganizationsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Remark,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = ?,
    remark = ?,
    sort_order = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateOrganizationParams struct {
	Name      string
	Remark    string
	SortOrder int64
	UpdatedAt dbtime.Time
	ID        string
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganization,
		arg.Name,
		arg.Remark,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :exec
UPDATE organizations SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateOrganizationStatusParams struct {
	Status    string
	UpdatedAt dbtime.Time
	ID        string
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganizationStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
