// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package sqlcgen

import (
	"context"
	"time"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (
    id, tenant_id, user_id, token_hash, channel, expires_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePasswordResetParams struct {
	ID        string
	TenantID  string
	UserID    string
	TokenHash string
	Channel   string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.Channel,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const getLivePasswordReset = `-- name: GetLivePasswordReset :one
SELECT id, tenant_id, user_id, token_hash, channel, expires_at, used_at, created_at FROM password_resets
WHERE tenant_id = $1
  AND token_hash = $2
  AND used_at IS NULL
  AND expires_at > $3
LIMIT 1
`

type GetLivePasswordResetParams struct {
	TenantID  string
	TokenHash string
	ExpiresAt time.Time
}

// A token is usable only if it is unspent and unexpired. Both conditions are
// in the query rather than checked afterwards, so a caller cannot act on a
// row it forgot to validate — there is no way to fetch a dead one.
func (q *Queries) GetLivePasswordReset(ctx context.Context, arg GetLivePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getLivePasswordReset, arg.TenantID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.Channel,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const spendPasswordReset = `-- name: SpendPasswordReset :exec
UPDATE password_resets SET used_at = $1 WHERE tenant_id = $2 AND id = $3
`

type SpendPasswordResetParams struct {
	UsedAt   *time.Time
	TenantID string
	ID       string
}

func (q *Queries) SpendPasswordReset(ctx context.Context, arg SpendPasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, spendPasswordReset, arg.UsedAt, arg.TenantID, arg.ID)
	return err
}

const supersedePasswordResets = `-- name: SupersedePasswordResets :exec
UPDATE password_resets
SET used_at = $1
WHERE tenant_id = $2 AND user_id = $3 AND used_at IS NULL
`

type SupersedePasswordResetsParams struct {
	UsedAt   *time.Time
	TenantID string
	UserID   string
}

// Marks a user's outstanding requests spent, so asking again invalidates the
// previous link. Without this, every request a user ever made stays live
// until it expires, and someone who has read one old message can use it.
func (q *Queries) SupersedePasswordResets(ctx context.Context, arg SupersedePasswordResetsParams) error {
	_, err := q.db.ExecContext(ctx, supersedePasswordResets, arg.UsedAt, arg.TenantID, arg.UserID)
	return err
}
