// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package sqlcgen

import (
	"context"
	"time"
)

const countRecentPasswordResets = `-- name: CountRecentPasswordResets :one
SELECT COUNT(*) FROM password_resets
WHERE tenant_id = $1 AND user_id = $2 AND created_at > $3
`

type CountRecentPasswordResetsParams struct {
	TenantID  string
	UserID    string
	CreatedAt time.Time
}

// How many reset messages this account has been sent lately.
//
// Counts rows rather than live tokens, and that is the point: a superseded
// row is a message that was already delivered, and SupersedePasswordResets
// marks every earlier request spent the moment a new one arrives. Counting
// only unspent rows would therefore always return one, and the cap would
// never fire.
//
// Safe against the retention sweep only because that sweep keeps thirty days
// and this window is one — see passwordResetRetention in internal/server. A
// retention shorter than the window would silently shrink it and leave a cap
// that cannot be reached.
func (q *Queries) CountRecentPasswordResets(ctx context.Context, arg CountRecentPasswordResetsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentPasswordResets, arg.TenantID, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (
    id, tenant_id, user_id, token_hash, channel, expires_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePasswordResetParams struct {
	ID        string
	TenantID  string
	UserID    string
	TokenHash string
	Channel   string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.Channel,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets
WHERE tenant_id = $1 AND expires_at < $2
`

type DeleteExpiredPasswordResetsParams struct {
	TenantID  string
	ExpiresAt time.Time
}

// Clears reset requests long past their usefulness.
//
// Spent and expired rows are kept for a retention window rather than deleted
// the moment they die, so that "was a reset link ever issued for this
// account, and was it used" stays answerable for a while after the fact. The
// audit trail records the request and the completion separately; this table
// is the operational copy, and it is the one that would otherwise grow
// without limit.
func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context, arg DeleteExpiredPasswordResetsParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResets, arg.TenantID, arg.ExpiresAt)
	return err
}

const getLivePasswordReset = `-- name: GetLivePasswordReset :one
SELECT id, tenant_id, user_id, token_hash, channel, expires_at, used_at, created_at FROM password_resets
WHERE tenant_id = $1
  AND token_hash = $2
  AND used_at IS NULL
  AND expires_at > $3
LIMIT 1
`

type GetLivePasswordResetParams struct {
	TenantID  string
	TokenHash string
	ExpiresAt time.Time
}

// A token is usable only if it is unspent and unexpired. Both conditions are
// in the query rather than checked afterwards, so a caller cannot act on a
// row it forgot to validate — there is no way to fetch a dead one.
func (q *Queries) GetLivePasswordReset(ctx context.Context, arg GetLivePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getLivePasswordReset, arg.TenantID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.Channel,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const recentPasswordHashes = `-- name: RecentPasswordHashes :many
SELECT password_hash FROM password_history
WHERE tenant_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type RecentPasswordHashesParams struct {
	TenantID string
	UserID   string
	Limit    int32
}

// The newest N hashes for an account, for a reuse check.
func (q *Queries) RecentPasswordHashes(ctx context.Context, arg RecentPasswordHashesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, recentPasswordHashes, arg.TenantID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var password_hash string
		if err := rows.Scan(&password_hash); err != nil {
			return nil, err
		}
		items = append(items, password_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPasswordInHistory = `-- name: RecordPasswordInHistory :exec
INSERT INTO password_history (id, tenant_id, user_id, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type RecordPasswordInHistoryParams struct {
	ID           string
	TenantID     string
	UserID       string
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) RecordPasswordInHistory(ctx context.Context, arg RecordPasswordInHistoryParams) error {
	_, err := q.db.ExecContext(ctx, recordPasswordInHistory,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const spendPasswordReset = `-- name: SpendPasswordReset :exec
UPDATE password_resets SET used_at = $1 WHERE tenant_id = $2 AND id = $3
`

type SpendPasswordResetParams struct {
	UsedAt   *time.Time
	TenantID string
	ID       string
}

func (q *Queries) SpendPasswordReset(ctx context.Context, arg SpendPasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, spendPasswordReset, arg.UsedAt, arg.TenantID, arg.ID)
	return err
}

const supersedePasswordResets = `-- name: SupersedePasswordResets :exec
UPDATE password_resets
SET used_at = $1
WHERE tenant_id = $2 AND user_id = $3 AND used_at IS NULL
`

type SupersedePasswordResetsParams struct {
	UsedAt   *time.Time
	TenantID string
	UserID   string
}

// Marks a user's outstanding requests spent, so asking again invalidates the
// previous link. Without this, every request a user ever made stays live
// until it expires, and someone who has read one old message can use it.
func (q *Queries) SupersedePasswordResets(ctx context.Context, arg SupersedePasswordResetsParams) error {
	_, err := q.db.ExecContext(ctx, supersedePasswordResets, arg.UsedAt, arg.TenantID, arg.UserID)
	return err
}

const trimPasswordHistory = `-- name: TrimPasswordHistory :exec
DELETE FROM password_history h
WHERE h.tenant_id = $1 AND h.user_id = $2 AND h.id NOT IN (
    SELECT keep.id FROM password_history keep
    WHERE keep.tenant_id = $1 AND keep.user_id = $2
    ORDER BY keep.created_at DESC
    LIMIT $3
)
`

type TrimPasswordHistoryParams struct {
	TenantID string
	UserID   string
	Limit    int32
}

// Drops everything past the depth now configured, so lowering the setting
// takes effect rather than leaving older entries consultable forever.
func (q *Queries) TrimPasswordHistory(ctx context.Context, arg TrimPasswordHistoryParams) error {
	_, err := q.db.ExecContext(ctx, trimPasswordHistory, arg.TenantID, arg.UserID, arg.Limit)
	return err
}
