// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_verification_codes.sql

package sqlcgen

import (
	"context"
	"time"
)

const consumePhoneVerificationCode = `-- name: ConsumePhoneVerificationCode :exec
UPDATE phone_verification_codes SET consumed_at = $3
WHERE tenant_id = $1 AND id = $2
`

type ConsumePhoneVerificationCodeParams struct {
	TenantID   string
	ID         string
	ConsumedAt *time.Time
}

func (q *Queries) ConsumePhoneVerificationCode(ctx context.Context, arg ConsumePhoneVerificationCodeParams) error {
	_, err := q.db.ExecContext(ctx, consumePhoneVerificationCode, arg.TenantID, arg.ID, arg.ConsumedAt)
	return err
}

const countRecentPhoneVerificationCodes = `-- name: CountRecentPhoneVerificationCodes :one
SELECT count(*) FROM phone_verification_codes
WHERE tenant_id = $1 AND user_id = $2 AND created_at > $3
`

type CountRecentPhoneVerificationCodesParams struct {
	TenantID  string
	UserID    string
	CreatedAt time.Time
}

// RequestPhoneChange's per-account daily cap, same shape as
// CountRecentPasswordResets -- rows, not live codes, so an already-consumed
// or superseded request still counts against the sender it was.
func (q *Queries) CountRecentPhoneVerificationCodes(ctx context.Context, arg CountRecentPhoneVerificationCodesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentPhoneVerificationCodes, arg.TenantID, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoneVerificationCode = `-- name: CreatePhoneVerificationCode :exec
INSERT INTO phone_verification_codes (
    id, tenant_id, user_id, phone, code_hash, expires_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePhoneVerificationCodeParams struct {
	ID        string
	TenantID  string
	UserID    string
	Phone     string
	CodeHash  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreatePhoneVerificationCode(ctx context.Context, arg CreatePhoneVerificationCodeParams) error {
	_, err := q.db.ExecContext(ctx, createPhoneVerificationCode,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredPhoneVerificationCodes = `-- name: DeleteExpiredPhoneVerificationCodes :exec
DELETE FROM phone_verification_codes
WHERE tenant_id = $1 AND expires_at < $2
`

type DeleteExpiredPhoneVerificationCodesParams struct {
	TenantID  string
	ExpiresAt time.Time
}

// Same retention shape as DeleteExpiredSMSLoginCodes.
func (q *Queries) DeleteExpiredPhoneVerificationCodes(ctx context.Context, arg DeleteExpiredPhoneVerificationCodesParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPhoneVerificationCodes, arg.TenantID, arg.ExpiresAt)
	return err
}

const getLivePhoneVerificationCode = `-- name: GetLivePhoneVerificationCode :one
SELECT id, tenant_id, user_id, phone, code_hash, attempts, consumed_at, expires_at, created_at FROM phone_verification_codes
WHERE tenant_id = $1
  AND user_id = $2
  AND phone = $3
  AND consumed_at IS NULL
  AND expires_at > $4
ORDER BY created_at DESC
LIMIT 1
`

type GetLivePhoneVerificationCodeParams struct {
	TenantID  string
	UserID    string
	Phone     string
	ExpiresAt time.Time
}

// The newest unconsumed, unexpired code this user has been sent for this
// candidate phone. Newest for the same reason GetLiveSMSLoginCode is:
// ConfirmPhoneChange does not know the code is right yet, and comparing
// against anything but the most recent request would let a superseded code
// still verify.
func (q *Queries) GetLivePhoneVerificationCode(ctx context.Context, arg GetLivePhoneVerificationCodeParams) (PhoneVerificationCode, error) {
	row := q.db.QueryRowContext(ctx, getLivePhoneVerificationCode,
		arg.TenantID,
		arg.UserID,
		arg.Phone,
		arg.ExpiresAt,
	)
	var i PhoneVerificationCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPhoneVerificationCodeAttempts = `-- name: IncrementPhoneVerificationCodeAttempts :exec
UPDATE phone_verification_codes SET attempts = attempts + 1
WHERE tenant_id = $1 AND id = $2
`

type IncrementPhoneVerificationCodeAttemptsParams struct {
	TenantID string
	ID       string
}

func (q *Queries) IncrementPhoneVerificationCodeAttempts(ctx context.Context, arg IncrementPhoneVerificationCodeAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, incrementPhoneVerificationCodeAttempts, arg.TenantID, arg.ID)
	return err
}
