// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saml_keys.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSAMLSigningKey = `-- name: CreateSAMLSigningKey :exec
INSERT INTO saml_signing_keys (
    id, tenant_id, private_key, certificate, status, created_at, expires_at
) VALUES ($1, $2, $3, $4, 'ACTIVE', $5, $6)
`

type CreateSAMLSigningKeyParams struct {
	ID          string
	TenantID    string
	PrivateKey  string
	Certificate string
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) CreateSAMLSigningKey(ctx context.Context, arg CreateSAMLSigningKeyParams) error {
	_, err := q.db.ExecContext(ctx, createSAMLSigningKey,
		arg.ID,
		arg.TenantID,
		arg.PrivateKey,
		arg.Certificate,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getActiveSAMLSigningKey = `-- name: GetActiveSAMLSigningKey :one
SELECT id, tenant_id, private_key, certificate, status, created_at, expires_at, retired_at FROM saml_signing_keys
WHERE tenant_id = $1 AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) GetActiveSAMLSigningKey(ctx context.Context, tenantID string) (SamlSigningKey, error) {
	row := q.db.QueryRowContext(ctx, getActiveSAMLSigningKey, tenantID)
	var i SamlSigningKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PrivateKey,
		&i.Certificate,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RetiredAt,
	)
	return i, err
}

const listSAMLSigningKeys = `-- name: ListSAMLSigningKeys :many
SELECT id, tenant_id, private_key, certificate, status, created_at, expires_at, retired_at FROM saml_signing_keys
WHERE tenant_id = $1
ORDER BY CASE WHEN status = 'ACTIVE' THEN 0 ELSE 1 END, created_at DESC
`

// Active first, then retired newest first. Retired keys are kept rather than
// deleted: a service provider pins the certificate in its own configuration
// and cannot be told to refetch, so an operator has to be able to see what
// the previous one was while service providers are being moved across.
func (q *Queries) ListSAMLSigningKeys(ctx context.Context, tenantID string) ([]SamlSigningKey, error) {
	rows, err := q.db.QueryContext(ctx, listSAMLSigningKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SamlSigningKey{}
	for rows.Next() {
		var i SamlSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PrivateKey,
			&i.Certificate,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireSAMLSigningKeys = `-- name: RetireSAMLSigningKeys :exec
UPDATE saml_signing_keys
SET status = 'RETIRED', retired_at = $1
WHERE tenant_id = $2 AND status = 'ACTIVE'
`

type RetireSAMLSigningKeysParams struct {
	RetiredAt *time.Time
	TenantID  string
}

func (q *Queries) RetireSAMLSigningKeys(ctx context.Context, arg RetireSAMLSigningKeysParams) error {
	_, err := q.db.ExecContext(ctx, retireSAMLSigningKeys, arg.RetiredAt, arg.TenantID)
	return err
}
