// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saml_providers.sql

package sqlcgen

import (
	"context"
	"time"
)

const completeSAMLAuthRequest = `-- name: CompleteSAMLAuthRequest :exec
UPDATE saml_auth_requests
SET subject = $1, done = TRUE
WHERE tenant_id = $2 AND id = $3
`

type CompleteSAMLAuthRequestParams struct {
	Subject  *string
	TenantID string
	ID       string
}

// Records who signed in. Until this runs the request has no subject and
// cannot produce an assertion.
func (q *Queries) CompleteSAMLAuthRequest(ctx context.Context, arg CompleteSAMLAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, completeSAMLAuthRequest, arg.Subject, arg.TenantID, arg.ID)
	return err
}

const createSAMLAuthRequest = `-- name: CreateSAMLAuthRequest :exec
INSERT INTO saml_auth_requests (
    id, tenant_id, issuer, request_xml, relay_state, sp_entity_id,
    created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSAMLAuthRequestParams struct {
	ID         string
	TenantID   string
	Issuer     string
	RequestXml string
	RelayState string
	SpEntityID string
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

func (q *Queries) CreateSAMLAuthRequest(ctx context.Context, arg CreateSAMLAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, createSAMLAuthRequest,
		arg.ID,
		arg.TenantID,
		arg.Issuer,
		arg.RequestXml,
		arg.RelayState,
		arg.SpEntityID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createSAMLServiceProvider = `-- name: CreateSAMLServiceProvider :exec
INSERT INTO saml_service_providers (
    id, tenant_id, entity_id, name, metadata_xml, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSAMLServiceProviderParams struct {
	ID          string
	TenantID    string
	EntityID    string
	Name        string
	MetadataXml string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateSAMLServiceProvider(ctx context.Context, arg CreateSAMLServiceProviderParams) error {
	_, err := q.db.ExecContext(ctx, createSAMLServiceProvider,
		arg.ID,
		arg.TenantID,
		arg.EntityID,
		arg.Name,
		arg.MetadataXml,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiredSAMLAuthRequests = `-- name: DeleteExpiredSAMLAuthRequests :exec
DELETE FROM saml_auth_requests WHERE tenant_id = $1 AND expires_at < $2
`

type DeleteExpiredSAMLAuthRequestsParams struct {
	TenantID  string
	ExpiresAt time.Time
}

func (q *Queries) DeleteExpiredSAMLAuthRequests(ctx context.Context, arg DeleteExpiredSAMLAuthRequestsParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSAMLAuthRequests, arg.TenantID, arg.ExpiresAt)
	return err
}

const deleteSAMLAuthRequest = `-- name: DeleteSAMLAuthRequest :exec
DELETE FROM saml_auth_requests WHERE tenant_id = $1 AND id = $2
`

type DeleteSAMLAuthRequestParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteSAMLAuthRequest(ctx context.Context, arg DeleteSAMLAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, deleteSAMLAuthRequest, arg.TenantID, arg.ID)
	return err
}

const getSAMLAuthRequest = `-- name: GetSAMLAuthRequest :one
SELECT id, tenant_id, issuer, request_xml, relay_state, sp_entity_id, subject, done, created_at, expires_at FROM saml_auth_requests
WHERE tenant_id = $1 AND id = $2 AND expires_at > $3
LIMIT 1
`

type GetSAMLAuthRequestParams struct {
	TenantID  string
	ID        string
	ExpiresAt time.Time
}

func (q *Queries) GetSAMLAuthRequest(ctx context.Context, arg GetSAMLAuthRequestParams) (SamlAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getSAMLAuthRequest, arg.TenantID, arg.ID, arg.ExpiresAt)
	var i SamlAuthRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Issuer,
		&i.RequestXml,
		&i.RelayState,
		&i.SpEntityID,
		&i.Subject,
		&i.Done,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSAMLServiceProvider = `-- name: GetSAMLServiceProvider :one
SELECT id, tenant_id, entity_id, name, metadata_xml, status, created_at, updated_at FROM saml_service_providers
WHERE tenant_id = $1 AND entity_id = $2
LIMIT 1
`

type GetSAMLServiceProviderParams struct {
	TenantID string
	EntityID string
}

func (q *Queries) GetSAMLServiceProvider(ctx context.Context, arg GetSAMLServiceProviderParams) (SamlServiceProvider, error) {
	row := q.db.QueryRowContext(ctx, getSAMLServiceProvider, arg.TenantID, arg.EntityID)
	var i SamlServiceProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityID,
		&i.Name,
		&i.MetadataXml,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSAMLServiceProviders = `-- name: ListSAMLServiceProviders :many
SELECT id, tenant_id, entity_id, name, metadata_xml, status, created_at, updated_at FROM saml_service_providers
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSAMLServiceProviders(ctx context.Context, tenantID string) ([]SamlServiceProvider, error) {
	rows, err := q.db.QueryContext(ctx, listSAMLServiceProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SamlServiceProvider{}
	for rows.Next() {
		var i SamlServiceProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.Name,
			&i.MetadataXml,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSAMLServiceProviderStatus = `-- name: UpdateSAMLServiceProviderStatus :exec
UPDATE saml_service_providers
SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND entity_id = $4
`

type UpdateSAMLServiceProviderStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	EntityID  string
}

func (q *Queries) UpdateSAMLServiceProviderStatus(ctx context.Context, arg UpdateSAMLServiceProviderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSAMLServiceProviderStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.EntityID,
	)
	return err
}
