// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSCIMCredential = `-- name: CreateSCIMCredential :exec
INSERT INTO scim_credentials (
    id, tenant_id, name, token_hash, token_prefix, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, 'ACTIVE', $6, $6)
`

type CreateSCIMCredentialParams struct {
	ID          string
	TenantID    string
	Name        string
	TokenHash   string
	TokenPrefix string
	CreatedAt   time.Time
}

func (q *Queries) CreateSCIMCredential(ctx context.Context, arg CreateSCIMCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMCredential,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.CreatedAt,
	)
	return err
}

const deleteSCIMCredential = `-- name: DeleteSCIMCredential :exec
DELETE FROM scim_credentials
WHERE tenant_id = $2 AND id = $1
`

type DeleteSCIMCredentialParams struct {
	ID       string
	TenantID string
}

// Deleted rather than disabled, unlike accounts and organizations. The rule
// there exists so the audit trail keeps naming the thing it refers to; a
// credential is named in the trail by the events it caused, which are
// unaffected by the row going away. Keeping revoked credentials forever
// would instead leave a list an operator has to read past to find the live
// ones.
func (q *Queries) DeleteSCIMCredential(ctx context.Context, arg DeleteSCIMCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteSCIMCredential, arg.ID, arg.TenantID)
	return err
}

const getSCIMCredentialByTokenHash = `-- name: GetSCIMCredentialByTokenHash :one
SELECT id, tenant_id, name, token_hash, token_prefix, status,
       last_used_at, created_at, updated_at
FROM scim_credentials
WHERE token_hash = $1
LIMIT 1
`

// Not tenant-scoped, and cannot be: this is the query that determines the
// tenant. A SCIM client presents a bearer token and nothing else — no
// session, no tenant header, no principal — so the credential row is the
// only thing that says which tenant the request acts in.
//
// Listed in internal/store/tenancy_guard_test.go as the second and only
// other unscoped query, beside GetUserForAuthentication, for the same
// reason: a filter here would have to be given the answer it is looking for.
//
// Disabled credentials are returned rather than filtered out, so the caller
// can distinguish "no such token" from "this integration was switched off"
// and say so — the second is worth a distinct answer to an operator staring
// at a directory that has stopped syncing.
func (q *Queries) GetSCIMCredentialByTokenHash(ctx context.Context, tokenHash string) (ScimCredential, error) {
	row := q.db.QueryRowContext(ctx, getSCIMCredentialByTokenHash, tokenHash)
	var i ScimCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, tenant_id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, external_id, failed_login_attempts, last_failed_login_at, locked_until, password_changed_at, created_at, updated_at, ldap_source_id, closed_at, verified_at, name_formatted, family_name, given_name, middle_name, honorific_prefix, honorific_suffix, nick_name, profile_url, photo_url, title, user_type, preferred_language, locale, timezone, address_formatted, street_address, locality, region, postal_code, country, employee_number, cost_center, department, manager_id, must_change_password, recovery_quota_cleared_at FROM users
WHERE tenant_id = $1 AND external_id = $2
LIMIT 1
`

type GetUserByExternalIDParams struct {
	TenantID   string
	ExternalID *string
}

func (q *Queries) GetUserByExternalID(ctx context.Context, arg GetUserByExternalIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalID, arg.TenantID, arg.ExternalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.OrganizationID,
		&i.TokenVersion,
		&i.Source,
		&i.ExternalID,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LdapSourceID,
		&i.ClosedAt,
		&i.VerifiedAt,
		&i.NameFormatted,
		&i.FamilyName,
		&i.GivenName,
		&i.MiddleName,
		&i.HonorificPrefix,
		&i.HonorificSuffix,
		&i.NickName,
		&i.ProfileUrl,
		&i.PhotoUrl,
		&i.Title,
		&i.UserType,
		&i.PreferredLanguage,
		&i.Locale,
		&i.Timezone,
		&i.AddressFormatted,
		&i.StreetAddress,
		&i.Locality,
		&i.Region,
		&i.PostalCode,
		&i.Country,
		&i.EmployeeNumber,
		&i.CostCenter,
		&i.Department,
		&i.ManagerID,
		&i.MustChangePassword,
		&i.RecoveryQuotaClearedAt,
	)
	return i, err
}

const listSCIMCredentials = `-- name: ListSCIMCredentials :many
SELECT id, tenant_id, name, token_hash, token_prefix, status,
       last_used_at, created_at, updated_at
FROM scim_credentials
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSCIMCredentials(ctx context.Context, tenantID string) ([]ScimCredential, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMCredentials, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScimCredential{}
	for rows.Next() {
		var i ScimCredential
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Status,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSCIMCredentialStatus = `-- name: SetSCIMCredentialStatus :exec
UPDATE scim_credentials
SET status = $2, updated_at = $3
WHERE tenant_id = $4 AND id = $1
`

type SetSCIMCredentialStatusParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
	TenantID  string
}

func (q *Queries) SetSCIMCredentialStatus(ctx context.Context, arg SetSCIMCredentialStatusParams) error {
	_, err := q.db.ExecContext(ctx, setSCIMCredentialStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
	)
	return err
}

const setUserExternalID = `-- name: SetUserExternalID :exec
UPDATE users
SET external_id = $2, updated_at = $3
WHERE tenant_id = $4 AND id = $1
`

type SetUserExternalIDParams struct {
	ID         string
	ExternalID *string
	UpdatedAt  time.Time
	TenantID   string
}

func (q *Queries) SetUserExternalID(ctx context.Context, arg SetUserExternalIDParams) error {
	_, err := q.db.ExecContext(ctx, setUserExternalID,
		arg.ID,
		arg.ExternalID,
		arg.UpdatedAt,
		arg.TenantID,
	)
	return err
}

const touchSCIMCredential = `-- name: TouchSCIMCredential :exec
UPDATE scim_credentials
SET last_used_at = $2
WHERE tenant_id = $3 AND id = $1
`

type TouchSCIMCredentialParams struct {
	ID         string
	LastUsedAt *time.Time
	TenantID   string
}

func (q *Queries) TouchSCIMCredential(ctx context.Context, arg TouchSCIMCredentialParams) error {
	_, err := q.db.ExecContext(ctx, touchSCIMCredential, arg.ID, arg.LastUsedAt, arg.TenantID)
	return err
}

const updateProvisionedUser = `-- name: UpdateProvisionedUser :exec
UPDATE users
SET username = $1,
    display_name = $2,
    phone = $3,
    email = $4,
    status = $5,
    external_id = $6,
    updated_at = $7
WHERE tenant_id = $8 AND id = $9
`

type UpdateProvisionedUserParams struct {
	Username    string
	DisplayName string
	Phone       string
	Email       string
	Status      string
	ExternalID  *string
	UpdatedAt   time.Time
	TenantID    string
	ID          string
}

// The directory's view of an account, written as one statement.
//
// Separate from UpdateUserProfile because it writes the username, which that
// one deliberately does not: in the console a rename is an administrator's
// decision about somebody else's account. Here the directory is the system of
// record — it is what the externalId points back to — and refusing its rename
// would leave the two permanently disagreeing, with every subsequent sync
// trying the same change again.
//
// Role and organization are absent, and that is the boundary: a directory may
// say who somebody is, and may not say what they may do. SCIM has no notion
// of Portico's roles, so a mapping would have to be invented, and an invented
// one is a way to grant administrator by writing an attribute.
func (q *Queries) UpdateProvisionedUser(ctx context.Context, arg UpdateProvisionedUserParams) error {
	_, err := q.db.ExecContext(ctx, updateProvisionedUser,
		arg.Username,
		arg.DisplayName,
		arg.Phone,
		arg.Email,
		arg.Status,
		arg.ExternalID,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}
