// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, tenant_id, user_id, ip, user_agent,
    created_at, last_seen_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $6, $7)
`

type CreateSessionParams struct {
	ID        string
	TenantID  string
	UserID    string
	Ip        string
	UserAgent string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE tenant_id = $1 AND expires_at < $2
`

type DeleteExpiredSessionsParams struct {
	TenantID  string
	ExpiresAt time.Time
}

// Rows past the retention window. A revoked or expired session is kept for a
// while so that "when did this end, and from where" stays answerable.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, arg.TenantID, arg.ExpiresAt)
	return err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, tenant_id, user_id, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM sessions
WHERE tenant_id = $1 AND id = $2 AND revoked_at IS NULL AND expires_at > $3
LIMIT 1
`

type GetLiveSessionParams struct {
	TenantID  string
	ID        string
	ExpiresAt time.Time
}

// A session is usable only if it is unrevoked and unexpired. Both conditions
// are in the query rather than checked afterwards, so a caller cannot act on
// a row it forgot to validate.
//
// Scoped by tenant as well as by id, even though an id is a UUID and
// collisions are not the concern: the tenant comes from the token, so a
// session cannot be presented against a tenant it was not issued in. That is
// the same guarantee the account lookup makes a few lines later, and there
// is no reason for this one to be weaker.
func (q *Queries) GetLiveSession(ctx context.Context, arg GetLiveSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getLiveSession, arg.TenantID, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, tenant_id, user_id, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM sessions
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL AND expires_at > $3
ORDER BY last_seen_at DESC
`

type ListSessionsForUserParams struct {
	TenantID  string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForUser, arg.TenantID, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = $1
WHERE tenant_id = $2 AND id = $3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt *time.Time
	TenantID  string
	ID        string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.RevokedAt, arg.TenantID, arg.ID)
	return err
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :exec
UPDATE sessions SET revoked_at = $1
WHERE tenant_id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type RevokeSessionsForUserParams struct {
	RevokedAt *time.Time
	TenantID  string
	UserID    string
}

// Every session an account has. Signing out everywhere, and what a disable
// or password change amounts to here.
func (q *Queries) RevokeSessionsForUser(ctx context.Context, arg RevokeSessionsForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsForUser, arg.RevokedAt, arg.TenantID, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $1 WHERE tenant_id = $2 AND id = $3
`

type TouchSessionParams struct {
	LastSeenAt time.Time
	TenantID   string
	ID         string
}

// Lazily updates last_seen_at. The caller decides how stale is stale enough
// to be worth a write; see auth.Middleware.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.TenantID, arg.ID)
	return err
}
