// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
	"time"
)

const getSetting = `-- name: GetSetting :one
SELECT tenant_id, key, value, updated_at FROM system_settings WHERE tenant_id = $1 AND key = $2 LIMIT 1
`

type GetSettingParams struct {
	TenantID string
	Key      string
}

func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, arg.TenantID, arg.Key)
	var i SystemSetting
	err := row.Scan(
		&i.TenantID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT tenant_id, key, value, updated_at FROM system_settings WHERE tenant_id = $1 ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context, tenantID string) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.TenantID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO system_settings (tenant_id, key, value, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, key) DO UPDATE
SET value = excluded.value, updated_at = excluded.updated_at
`

type UpsertSettingParams struct {
	TenantID  string
	Key       string
	Value     string
	UpdatedAt time.Time
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.TenantID,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}
