// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"

	dbtime "github.com/paraview/portico/internal/store/dbtime"
)

const getSetting = `-- name: GetSetting :one
SELECT "key", value, updated_at FROM system_settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i SystemSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value, updated_at FROM system_settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO system_settings (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type UpsertSettingParams struct {
	Key       string
	Value     string
	UpdatedAt dbtime.Time
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
