// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sms_login_codes.sql

package sqlcgen

import (
	"context"
	"time"
)

const consumeSMSLoginCode = `-- name: ConsumeSMSLoginCode :exec
UPDATE sms_login_codes SET consumed_at = $3
WHERE tenant_id = $1 AND id = $2
`

type ConsumeSMSLoginCodeParams struct {
	TenantID   string
	ID         string
	ConsumedAt *time.Time
}

func (q *Queries) ConsumeSMSLoginCode(ctx context.Context, arg ConsumeSMSLoginCodeParams) error {
	_, err := q.db.ExecContext(ctx, consumeSMSLoginCode, arg.TenantID, arg.ID, arg.ConsumedAt)
	return err
}

const createSMSLoginCode = `-- name: CreateSMSLoginCode :exec
INSERT INTO sms_login_codes (
    id, tenant_id, phone, code_hash, expires_at, created_at, ip
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSMSLoginCodeParams struct {
	ID        string
	TenantID  string
	Phone     string
	CodeHash  string
	ExpiresAt time.Time
	CreatedAt time.Time
	Ip        string
}

func (q *Queries) CreateSMSLoginCode(ctx context.Context, arg CreateSMSLoginCodeParams) error {
	_, err := q.db.ExecContext(ctx, createSMSLoginCode,
		arg.ID,
		arg.TenantID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.Ip,
	)
	return err
}

const deleteExpiredSMSLoginCodes = `-- name: DeleteExpiredSMSLoginCodes :exec
DELETE FROM sms_login_codes
WHERE tenant_id = $1 AND expires_at < $2
`

type DeleteExpiredSMSLoginCodesParams struct {
	TenantID  string
	ExpiresAt time.Time
}

// Same retention shape as DeleteExpiredPasswordResets: clears rows well
// past their usefulness rather than deleting them the instant they expire.
func (q *Queries) DeleteExpiredSMSLoginCodes(ctx context.Context, arg DeleteExpiredSMSLoginCodesParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSMSLoginCodes, arg.TenantID, arg.ExpiresAt)
	return err
}

const getLiveSMSLoginCode = `-- name: GetLiveSMSLoginCode :one
SELECT id, tenant_id, phone, code_hash, attempts, consumed_at, expires_at, created_at, ip FROM sms_login_codes
WHERE tenant_id = $1
  AND phone = $2
  AND consumed_at IS NULL
  AND expires_at > $3
ORDER BY created_at DESC
LIMIT 1
`

type GetLiveSMSLoginCodeParams struct {
	TenantID  string
	Phone     string
	ExpiresAt time.Time
}

// The newest unconsumed, unexpired code for this tenant's phone number.
// Newest rather than "the one matching the code" because the caller does
// not know the code is right yet -- it has to compare the hash itself,
// and comparing against anything but the most recent request would let an
// old, superseded code still verify.
func (q *Queries) GetLiveSMSLoginCode(ctx context.Context, arg GetLiveSMSLoginCodeParams) (SmsLoginCode, error) {
	row := q.db.QueryRowContext(ctx, getLiveSMSLoginCode, arg.TenantID, arg.Phone, arg.ExpiresAt)
	var i SmsLoginCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Ip,
	)
	return i, err
}

const incrementSMSLoginCodeAttempts = `-- name: IncrementSMSLoginCodeAttempts :exec
UPDATE sms_login_codes SET attempts = attempts + 1
WHERE tenant_id = $1 AND id = $2
`

type IncrementSMSLoginCodeAttemptsParams struct {
	TenantID string
	ID       string
}

func (q *Queries) IncrementSMSLoginCodeAttempts(ctx context.Context, arg IncrementSMSLoginCodeAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, incrementSMSLoginCodeAttempts, arg.TenantID, arg.ID)
	return err
}
