// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlcgen

import (
	"context"
	"time"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, code, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTenantParams struct {
	ID        string
	Code      string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTenantByCode = `-- name: GetTenantByCode :one
SELECT id, code, name, status, created_at, updated_at FROM tenants WHERE code = $1 LIMIT 1
`

func (q *Queries) GetTenantByCode(ctx context.Context, code string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByCode, code)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one

SELECT id, code, name, status, created_at, updated_at FROM tenants WHERE id = $1 LIMIT 1
`

// Tenants are the root of the isolation hierarchy, so unlike every other
// table these queries are not scoped by tenant_id — there is nothing above a
// tenant to scope them to. They are reachable only from the provisioning CLI
// and from sign-in's tenant resolution, never from an authenticated request
// handler.
func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, code, name, status, created_at, updated_at FROM tenants ORDER BY code
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants SET status = $1, updated_at = $2 WHERE id = $3
`

type UpdateTenantStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
