// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlcgen

import (
	"context"
	"time"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, code, name, status, created_at, updated_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTenantParams struct {
	ID        string
	Code      string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt *time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

// Everything scoped to this tenant goes with it, by ON DELETE CASCADE.
func (q *Queries) DeleteTenant(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTenant, id)
	return err
}

const getTenantByCode = `-- name: GetTenantByCode :one
SELECT id, code, name, status, created_at, updated_at, expires_at FROM tenants WHERE code = $1 LIMIT 1
`

func (q *Queries) GetTenantByCode(ctx context.Context, code string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByCode, code)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one

SELECT id, code, name, status, created_at, updated_at, expires_at FROM tenants WHERE id = $1 LIMIT 1
`

// Tenants are the root of the isolation hierarchy, so unlike every other
// table these queries are not scoped by tenant_id — there is nothing above a
// tenant to scope them to.
//
// Everything here except TenantOverview is reachable only from the
// provisioning CLI and from sign-in's tenant resolution. TenantOverview is
// the single exception and the only query in this system an authenticated
// request can use to learn that another tenant exists; what stands in front
// of it is a route that is not registered unless PORTICO_TENANT_CONSOLE is
// on, and then only for an administrator of the default tenant. See
// internal/server/routes.go and docs/access-guide.md.
func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, code, name, status, created_at, updated_at, expires_at FROM tenants ORDER BY code
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsToDelete = `-- name: ListTenantsToDelete :many
SELECT id, code, name, status, created_at, updated_at, expires_at FROM tenants
WHERE expires_at IS NOT NULL AND expires_at <= $1
ORDER BY expires_at
`

// Tenants whose grace period has also passed.
//
// Separate from the query above rather than one query with two cases, because
// these two do very different things: one is reversible and one is not. A
// caller has to ask for the destructive list by name.
func (q *Queries) ListTenantsToDelete(ctx context.Context, expiresAt *time.Time) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsToDelete, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsToDisable = `-- name: ListTenantsToDisable :many
SELECT id, code, name, status, created_at, updated_at, expires_at FROM tenants
WHERE expires_at IS NOT NULL AND expires_at <= $1 AND status = 'ACTIVE'
ORDER BY expires_at
`

// Tenants whose deadline has passed while they are still able to sign in.
//
// Status is part of the predicate so the sweep is idempotent: once disabled, a
// tenant stops appearing here and is not written to on every pass.
func (q *Queries) ListTenantsToDisable(ctx context.Context, expiresAt *time.Time) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsToDisable, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantExpiry = `-- name: SetTenantExpiry :exec
UPDATE tenants SET expires_at = $1, updated_at = $2 WHERE id = $3
`

type SetTenantExpiryParams struct {
	ExpiresAt *time.Time
	UpdatedAt time.Time
	ID        string
}

// Moves a deadline, or removes one with NULL.
func (q *Queries) SetTenantExpiry(ctx context.Context, arg SetTenantExpiryParams) error {
	_, err := q.db.ExecContext(ctx, setTenantExpiry, arg.ExpiresAt, arg.UpdatedAt, arg.ID)
	return err
}

const tenantOverview = `-- name: TenantOverview :many
SELECT
    t.id,
    t.code,
    t.name,
    t.status,
    t.created_at,
    -- The deadline, so the console can show how long a trial tenant has left
    -- without a second query. NULL for every tenant nobody gave one to.
    t.expires_at,
    (SELECT count(*) FROM users u
        WHERE u.tenant_id = t.id) AS user_count,
    (SELECT count(*) FROM users u
        WHERE u.tenant_id = t.id AND u.status = 'ACTIVE') AS active_user_count,
    (SELECT count(*) FROM organizations o
        WHERE o.tenant_id = t.id) AS organization_count,
    ((SELECT count(*) FROM oauth_clients c
        WHERE c.tenant_id = t.id)
      + (SELECT count(*) FROM saml_service_providers s
        WHERE s.tenant_id = t.id)
      + (SELECT count(*) FROM cas_services v
        WHERE v.tenant_id = t.id))::bigint AS application_count,
    -- When anything last happened in there, which is what separates a tenant
    -- in use from one that was created and forgotten. An index-only read:
    -- idx_audit_logs_created is (tenant_id, created_at DESC).
    (SELECT max(a.created_at) FROM audit_logs a
        WHERE a.tenant_id = t.id) AS last_activity
FROM tenants t
ORDER BY t.code
`

type TenantOverviewRow struct {
	ID                string
	Code              string
	Name              string
	Status            string
	CreatedAt         time.Time
	ExpiresAt         *time.Time
	UserCount         int64
	ActiveUserCount   int64
	OrganizationCount int64
	ApplicationCount  int64
	LastActivity      interface{}
}

// Every tenant with a count of what is inside it, for the operator console.
//
// The counts are correlated subqueries rather than a join with GROUP BY so
// that a tenant holding nothing still appears with zeros — a tenant somebody
// created and never used is exactly the row an operator is looking for.
//
// Note what this is and is not. Every read of a tenant-scoped table here
// carries a tenant_id predicate, as the isolation guard demands; what is new
// is that the predicate iterates over the tenants rather than being fixed to
// the caller's own. So no row of another tenant's data leaves — only how many
// of them there are. That distinction is the whole design of this feature,
// and it is why nothing below selects a name, an address, or an identifier
// belonging to a tenant other than through the tenants table itself.
//
// An application is counted across the three kinds the console registers, so
// the number agrees with what that tenant's own Applications page shows.
func (q *Queries) TenantOverview(ctx context.Context) ([]TenantOverviewRow, error) {
	rows, err := q.db.QueryContext(ctx, tenantOverview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantOverviewRow{}
	for rows.Next() {
		var i TenantOverviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UserCount,
			&i.ActiveUserCount,
			&i.OrganizationCount,
			&i.ApplicationCount,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants SET status = $1, updated_at = $2 WHERE id = $3
`

type UpdateTenantStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
