// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_requests.sql

package sqlcgen

import (
	"context"
	"time"
)

const countConfirmedTrials = `-- name: CountConfirmedTrials :one
SELECT count(*) FROM trial_requests WHERE confirmed_at IS NOT NULL
`

// The global quota. Confirmed only: a pending request has cost nothing yet.
func (q *Queries) CountConfirmedTrials(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfirmedTrials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConfirmedTrialsForEmail = `-- name: CountConfirmedTrialsForEmail :one
SELECT count(*) FROM trial_requests
WHERE email = $1 AND confirmed_at IS NOT NULL
`

// Whether this address already has a tenant.
//
// Checked at request time as well as enforced by the index, because the index
// is partial on confirmed rows: a second *pending* request for the same
// address does not collide with it, so without this read the visitor is told
// to check their email and only discovers the refusal after clicking — with a
// tenant already created for their first request.
func (q *Queries) CountConfirmedTrialsForEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfirmedTrialsForEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentTrialRequestsFromIP = `-- name: CountRecentTrialRequestsFromIP :one
SELECT count(*) FROM trial_requests
WHERE request_ip = $1 AND created_at > $2
`

type CountRecentTrialRequestsFromIPParams struct {
	RequestIp string
	CreatedAt time.Time
}

// The rate limiter's slower cousin — one address opening tenants steadily
// rather than quickly, which per-minute limiting does not see.
func (q *Queries) CountRecentTrialRequestsFromIP(ctx context.Context, arg CountRecentTrialRequestsFromIPParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentTrialRequestsFromIP, arg.RequestIp, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrialRequest = `-- name: CreateTrialRequest :one

INSERT INTO trial_requests (
    id, email, company_name, tenant_code, industry,
    token_hash, expires_at, request_ip
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, company_name, tenant_code, industry, token_hash, expires_at, confirmed_at, tenant_id, request_ip, created_at
`

type CreateTrialRequestParams struct {
	ID          string
	Email       string
	CompanyName string
	TenantCode  string
	Industry    string
	TokenHash   string
	ExpiresAt   time.Time
	RequestIp   string
}

// Self-service trial signups. Unscoped, unlike everything else here: these
// rows are what exists before a tenant does. See migrations/00023.
// Reserves the code and the address in one statement. A duplicate code or a
// second confirmed request for the same address is refused by the indexes
// rather than by a prior read, because two clicks arriving together would
// both pass a read.
func (q *Queries) CreateTrialRequest(ctx context.Context, arg CreateTrialRequestParams) (TrialRequest, error) {
	row := q.db.QueryRowContext(ctx, createTrialRequest,
		arg.ID,
		arg.Email,
		arg.CompanyName,
		arg.TenantCode,
		arg.Industry,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RequestIp,
	)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.TenantCode,
		&i.Industry,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.TenantID,
		&i.RequestIp,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTrialRequests = `-- name: DeleteExpiredTrialRequests :execrows
DELETE FROM trial_requests
WHERE confirmed_at IS NULL AND expires_at < now()
`

// Returns a reserved code to circulation. Unconfirmed only: a confirmed
// request is the record of a tenant that exists.
func (q *Queries) DeleteExpiredTrialRequests(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredTrialRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTrialRequestByTenant = `-- name: DeleteTrialRequestByTenant :execrows
DELETE FROM trial_requests WHERE tenant_id = $1
`

// Releases the address and the code together with the tenant they named. Kept
// separate from deleting the tenant so that the order is visible at the call
// site: this row is what the foreign key points from.
func (q *Queries) DeleteTrialRequestByTenant(ctx context.Context, tenantID *string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrialRequestByTenant, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTrialRequestByToken = `-- name: DeleteTrialRequestByToken :execrows
DELETE FROM trial_requests WHERE token_hash = $1 AND confirmed_at IS NULL
`

// Reverses a reservation whose link could not be sent. The address and the
// code are held by the row, so a failed send has to release them or the
// visitor cannot retry with the details they just typed.
func (q *Queries) DeleteTrialRequestByToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrialRequestByToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getConfirmedTrialByTenantCode = `-- name: GetConfirmedTrialByTenantCode :one
SELECT r.id, r.email, r.tenant_id, r.confirmed_at
FROM trial_requests r
JOIN tenants t ON t.id = r.tenant_id
WHERE t.code = $1 AND r.confirmed_at IS NOT NULL
`

type GetConfirmedTrialByTenantCodeRow struct {
	ID          string
	Email       string
	TenantID    *string
	ConfirmedAt *time.Time
}

// Whether a tenant came from a trial, which is what bounds what the command
// line is allowed to delete. A tenant nobody can find here was provisioned by
// hand and is not this command's business.
func (q *Queries) GetConfirmedTrialByTenantCode(ctx context.Context, code string) (GetConfirmedTrialByTenantCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getConfirmedTrialByTenantCode, code)
	var i GetConfirmedTrialByTenantCodeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.ConfirmedAt,
	)
	return i, err
}

const getTrialRequestByToken = `-- name: GetTrialRequestByToken :one
SELECT id, email, company_name, tenant_code, industry, token_hash, expires_at, confirmed_at, tenant_id, request_ip, created_at FROM trial_requests WHERE token_hash = $1
`

// What a followed link resolves to. Returns the row whatever its state: an
// already-confirmed request and an expired one need different answers, and
// both are better than "no such link".
func (q *Queries) GetTrialRequestByToken(ctx context.Context, tokenHash string) (TrialRequest, error) {
	row := q.db.QueryRowContext(ctx, getTrialRequestByToken, tokenHash)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.TenantCode,
		&i.Industry,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.TenantID,
		&i.RequestIp,
		&i.CreatedAt,
	)
	return i, err
}

const listConfirmedTrials = `-- name: ListConfirmedTrials :many
SELECT
    t.code AS tenant_code,
    t.name AS tenant_name,
    t.status AS tenant_status,
    r.email,
    r.industry,
    r.confirmed_at,
    r.request_ip
FROM trial_requests r
JOIN tenants t ON t.id = r.tenant_id
WHERE r.confirmed_at IS NOT NULL
ORDER BY r.confirmed_at DESC
`

type ListConfirmedTrialsRow struct {
	TenantCode   string
	TenantName   string
	TenantStatus string
	Email        string
	Industry     string
	ConfirmedAt  *time.Time
	RequestIp    string
}

// The confirmed trials and the tenants they produced, for the command line.
//
// A join rather than two reads because the interesting row is the pair: a
// tenant that came from a trial, and the address that asked for it. Neither
// table alone can say which tenants a stranger created.
func (q *Queries) ListConfirmedTrials(ctx context.Context) ([]ListConfirmedTrialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfirmedTrials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfirmedTrialsRow{}
	for rows.Next() {
		var i ListConfirmedTrialsRow
		if err := rows.Scan(
			&i.TenantCode,
			&i.TenantName,
			&i.TenantStatus,
			&i.Email,
			&i.Industry,
			&i.ConfirmedAt,
			&i.RequestIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTrialRequestConfirmed = `-- name: MarkTrialRequestConfirmed :one
UPDATE trial_requests
SET confirmed_at = now(), tenant_id = $2
WHERE id = $1 AND confirmed_at IS NULL
RETURNING id, email, company_name, tenant_code, industry, token_hash, expires_at, confirmed_at, tenant_id, request_ip, created_at
`

type MarkTrialRequestConfirmedParams struct {
	ID       string
	TenantID *string
}

// Spends the link and records what it produced.
//
// The WHERE clause carries confirmed_at IS NULL rather than trusting the read
// above: two clicks on the same link a moment apart both find a pending row,
// and only one of them may create a tenant.
func (q *Queries) MarkTrialRequestConfirmed(ctx context.Context, arg MarkTrialRequestConfirmedParams) (TrialRequest, error) {
	row := q.db.QueryRowContext(ctx, markTrialRequestConfirmed, arg.ID, arg.TenantID)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.TenantCode,
		&i.Industry,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.TenantID,
		&i.RequestIp,
		&i.CreatedAt,
	)
	return i, err
}
