// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_requests.sql

package sqlcgen

import (
	"context"
	"time"
)

const countConfirmedTrials = `-- name: CountConfirmedTrials :one
SELECT count(*) FROM trial_requests WHERE confirmed_at IS NOT NULL
`

// The global quota. Confirmed only: a pending request has cost nothing yet.
func (q *Queries) CountConfirmedTrials(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfirmedTrials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConfirmedTrialsForEmail = `-- name: CountConfirmedTrialsForEmail :one
SELECT count(*) FROM trial_requests
WHERE email = $1 AND confirmed_at IS NOT NULL
`

// Whether this address already has a tenant.
//
// Checked at request time as well as enforced by the index, because the index
// is partial on confirmed rows: a second *pending* request for the same
// address does not collide with it, so without this read the visitor is told
// to check their email and only discovers the refusal after clicking — with a
// tenant already created for their first request.
func (q *Queries) CountConfirmedTrialsForEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfirmedTrialsForEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentTrialRequestsFromIP = `-- name: CountRecentTrialRequestsFromIP :one
SELECT count(*) FROM trial_requests
WHERE request_ip = $1 AND created_at > $2
`

type CountRecentTrialRequestsFromIPParams struct {
	RequestIp string
	CreatedAt time.Time
}

// The rate limiter's slower cousin — one address opening tenants steadily
// rather than quickly, which per-minute limiting does not see.
func (q *Queries) CountRecentTrialRequestsFromIP(ctx context.Context, arg CountRecentTrialRequestsFromIPParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentTrialRequestsFromIP, arg.RequestIp, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrialRequest = `-- name: CreateTrialRequest :one

INSERT INTO trial_requests (
    id, email, company_name, tenant_code, industry,
    token_hash, expires_at, request_ip
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, company_name, tenant_code, industry, token_hash, expires_at, confirmed_at, tenant_id, request_ip, created_at
`

type CreateTrialRequestParams struct {
	ID          string
	Email       string
	CompanyName string
	TenantCode  string
	Industry    string
	TokenHash   string
	ExpiresAt   time.Time
	RequestIp   string
}

// Self-service trial signups. Unscoped, unlike everything else here: these
// rows are what exists before a tenant does. See migrations/00023.
// Reserves the code and the address in one statement. A duplicate code or a
// second confirmed request for the same address is refused by the indexes
// rather than by a prior read, because two clicks arriving together would
// both pass a read.
func (q *Queries) CreateTrialRequest(ctx context.Context, arg CreateTrialRequestParams) (TrialRequest, error) {
	row := q.db.QueryRowContext(ctx, createTrialRequest,
		arg.ID,
		arg.Email,
		arg.CompanyName,
		arg.TenantCode,
		arg.Industry,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RequestIp,
	)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.TenantCode,
		&i.Industry,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.TenantID,
		&i.RequestIp,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTrialRequests = `-- name: DeleteExpiredTrialRequests :execrows
DELETE FROM trial_requests
WHERE confirmed_at IS NULL AND expires_at < now()
`

// Returns a reserved code to circulation. Unconfirmed only: a confirmed
// request is the record of a tenant that exists.
func (q *Queries) DeleteExpiredTrialRequests(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredTrialRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTrialRequestByToken = `-- name: DeleteTrialRequestByToken :execrows
DELETE FROM trial_requests WHERE token_hash = $1 AND confirmed_at IS NULL
`

// Reverses a reservation whose link could not be sent. The address and the
// code are held by the row, so a failed send has to release them or the
// visitor cannot retry with the details they just typed.
func (q *Queries) DeleteTrialRequestByToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrialRequestByToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTrialRequestByToken = `-- name: GetTrialRequestByToken :one
SELECT id, email, company_name, tenant_code, industry, token_hash, expires_at, confirmed_at, tenant_id, request_ip, created_at FROM trial_requests WHERE token_hash = $1
`

// What a followed link resolves to. Returns the row whatever its state: an
// already-confirmed request and an expired one need different answers, and
// both are better than "no such link".
func (q *Queries) GetTrialRequestByToken(ctx context.Context, tokenHash string) (TrialRequest, error) {
	row := q.db.QueryRowContext(ctx, getTrialRequestByToken, tokenHash)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.TenantCode,
		&i.Industry,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.TenantID,
		&i.RequestIp,
		&i.CreatedAt,
	)
	return i, err
}

const markTrialRequestConfirmed = `-- name: MarkTrialRequestConfirmed :one
UPDATE trial_requests
SET confirmed_at = now(), tenant_id = $2
WHERE id = $1 AND confirmed_at IS NULL
RETURNING id, email, company_name, tenant_code, industry, token_hash, expires_at, confirmed_at, tenant_id, request_ip, created_at
`

type MarkTrialRequestConfirmedParams struct {
	ID       string
	TenantID *string
}

// Spends the link and records what it produced.
//
// The WHERE clause carries confirmed_at IS NULL rather than trusting the read
// above: two clicks on the same link a moment apart both find a pending row,
// and only one of them may create a tenant.
func (q *Queries) MarkTrialRequestConfirmed(ctx context.Context, arg MarkTrialRequestConfirmedParams) (TrialRequest, error) {
	row := q.db.QueryRowContext(ctx, markTrialRequestConfirmed, arg.ID, arg.TenantID)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.TenantCode,
		&i.Industry,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.TenantID,
		&i.RequestIp,
		&i.CreatedAt,
	)
	return i, err
}
