// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_attributes.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const countUserAttributeDefinitions = `-- name: CountUserAttributeDefinitions :one
SELECT count(*) FROM user_attribute_definitions WHERE tenant_id = $1
`

// For the per-tenant bound, which exists because every definition is a
// candidate for outbound mapping and a mapped attribute is bytes in a token.
func (q *Queries) CountUserAttributeDefinitions(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAttributeDefinitions, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserAttributeValues = `-- name: CountUserAttributeValues :one
SELECT count(*) FROM user_attribute_values
WHERE tenant_id = $1 AND definition_id = $2
`

type CountUserAttributeValuesParams struct {
	TenantID     string
	DefinitionID string
}

// Answers "who has filled this in", asked before retiring or mapping one.
func (q *Queries) CountUserAttributeValues(ctx context.Context, arg CountUserAttributeValuesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAttributeValues, arg.TenantID, arg.DefinitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserAttributeDefinition = `-- name: CreateUserAttributeDefinition :exec
INSERT INTO user_attribute_definitions (
    id, tenant_id, key, label, description, kind, allowed_values,
    required, sort_order, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateUserAttributeDefinitionParams struct {
	ID            string
	TenantID      string
	Key           string
	Label         string
	Description   string
	Kind          string
	AllowedValues json.RawMessage
	Required      bool
	SortOrder     int32
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUserAttributeDefinition(ctx context.Context, arg CreateUserAttributeDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, createUserAttributeDefinition,
		arg.ID,
		arg.TenantID,
		arg.Key,
		arg.Label,
		arg.Description,
		arg.Kind,
		arg.AllowedValues,
		arg.Required,
		arg.SortOrder,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUserAttributeDefinition = `-- name: DeleteUserAttributeDefinition :exec
DELETE FROM user_attribute_definitions WHERE tenant_id = $1 AND id = $2
`

type DeleteUserAttributeDefinitionParams struct {
	TenantID string
	ID       string
}

// Discards every value recorded against it, by the cascade. Disabling is the
// ordinary way to retire one; this is the other way, and the console says so.
func (q *Queries) DeleteUserAttributeDefinition(ctx context.Context, arg DeleteUserAttributeDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserAttributeDefinition, arg.TenantID, arg.ID)
	return err
}

const deleteUserAttributeValue = `-- name: DeleteUserAttributeValue :exec
DELETE FROM user_attribute_values
WHERE tenant_id = $1 AND user_id = $2 AND definition_id = $3
`

type DeleteUserAttributeValueParams struct {
	TenantID     string
	UserID       string
	DefinitionID string
}

// Clearing a value removes the row rather than storing an empty string, so
// that "never filled in" and "deliberately blank" do not become the same
// state — the outbound rule is that nothing is sent empty, and a row holding
// an empty string would be a value that is silently never sent.
func (q *Queries) DeleteUserAttributeValue(ctx context.Context, arg DeleteUserAttributeValueParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserAttributeValue, arg.TenantID, arg.UserID, arg.DefinitionID)
	return err
}

const getUserAttributeDefinition = `-- name: GetUserAttributeDefinition :one
SELECT id, tenant_id, key, label, description, kind, allowed_values, required, sort_order, status, created_at, updated_at FROM user_attribute_definitions
WHERE tenant_id = $1 AND id = $2 LIMIT 1
`

type GetUserAttributeDefinitionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetUserAttributeDefinition(ctx context.Context, arg GetUserAttributeDefinitionParams) (UserAttributeDefinition, error) {
	row := q.db.QueryRowContext(ctx, getUserAttributeDefinition, arg.TenantID, arg.ID)
	var i UserAttributeDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.Kind,
		&i.AllowedValues,
		&i.Required,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAttributeDefinitionByKey = `-- name: GetUserAttributeDefinitionByKey :one
SELECT id, tenant_id, key, label, description, kind, allowed_values, required, sort_order, status, created_at, updated_at FROM user_attribute_definitions
WHERE tenant_id = $1 AND key = $2 LIMIT 1
`

type GetUserAttributeDefinitionByKeyParams struct {
	TenantID string
	Key      string
}

func (q *Queries) GetUserAttributeDefinitionByKey(ctx context.Context, arg GetUserAttributeDefinitionByKeyParams) (UserAttributeDefinition, error) {
	row := q.db.QueryRowContext(ctx, getUserAttributeDefinitionByKey, arg.TenantID, arg.Key)
	var i UserAttributeDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.Kind,
		&i.AllowedValues,
		&i.Required,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAttributeDefinitions = `-- name: ListUserAttributeDefinitions :many
SELECT id, tenant_id, key, label, description, kind, allowed_values, required, sort_order, status, created_at, updated_at FROM user_attribute_definitions
WHERE tenant_id = $1
ORDER BY sort_order, key
`

// The tenant's own attribute definitions, in the order a form draws them.
// Disabled ones are included: the console shows them so they can be enabled
// again, and the catalogue marks them rather than hiding them.
func (q *Queries) ListUserAttributeDefinitions(ctx context.Context, tenantID string) ([]UserAttributeDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listUserAttributeDefinitions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAttributeDefinition{}
	for rows.Next() {
		var i UserAttributeDefinition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Key,
			&i.Label,
			&i.Description,
			&i.Kind,
			&i.AllowedValues,
			&i.Required,
			&i.SortOrder,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAttributeValues = `-- name: ListUserAttributeValues :many
SELECT v.definition_id, d.key, d.kind, v.value
FROM user_attribute_values v
JOIN user_attribute_definitions d ON d.id = v.definition_id
WHERE v.tenant_id = $1 AND v.user_id = $2 AND d.status = 'ACTIVE'
ORDER BY d.sort_order, d.key
`

type ListUserAttributeValuesParams struct {
	TenantID string
	UserID   string
}

type ListUserAttributeValuesRow struct {
	DefinitionID string
	Key          string
	Kind         string
	Value        string
}

// One account's custom values, joined to their definitions so a caller has
// the key and the kind without a second query. Disabled definitions are left
// out: a value that is not being sent and not being shown is not part of the
// account as anybody sees it.
func (q *Queries) ListUserAttributeValues(ctx context.Context, arg ListUserAttributeValuesParams) ([]ListUserAttributeValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserAttributeValues, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAttributeValuesRow{}
	for rows.Next() {
		var i ListUserAttributeValuesRow
		if err := rows.Scan(
			&i.DefinitionID,
			&i.Key,
			&i.Kind,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAttributeValue = `-- name: SetUserAttributeValue :exec
INSERT INTO user_attribute_values (
    tenant_id, user_id, definition_id, value, updated_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, definition_id)
DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at
`

type SetUserAttributeValueParams struct {
	TenantID     string
	UserID       string
	DefinitionID string
	Value        string
	UpdatedAt    time.Time
}

func (q *Queries) SetUserAttributeValue(ctx context.Context, arg SetUserAttributeValueParams) error {
	_, err := q.db.ExecContext(ctx, setUserAttributeValue,
		arg.TenantID,
		arg.UserID,
		arg.DefinitionID,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const updateUserAttributeDefinition = `-- name: UpdateUserAttributeDefinition :exec
UPDATE user_attribute_definitions
SET label = $1,
    description = $2,
    kind = $3,
    allowed_values = $4,
    required = $5,
    sort_order = $6,
    updated_at = $7
WHERE tenant_id = $8 AND id = $9
`

type UpdateUserAttributeDefinitionParams struct {
	Label         string
	Description   string
	Kind          string
	AllowedValues json.RawMessage
	Required      bool
	SortOrder     int32
	UpdatedAt     time.Time
	TenantID      string
	ID            string
}

// The key is not in the SET list. It is what a mapping stores, so renaming it
// would silently stop a mapping that names it — in a system Portico does not
// own and cannot warn.
func (q *Queries) UpdateUserAttributeDefinition(ctx context.Context, arg UpdateUserAttributeDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAttributeDefinition,
		arg.Label,
		arg.Description,
		arg.Kind,
		arg.AllowedValues,
		arg.Required,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateUserAttributeDefinitionStatus = `-- name: UpdateUserAttributeDefinitionStatus :exec
UPDATE user_attribute_definitions
SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateUserAttributeDefinitionStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) UpdateUserAttributeDefinitionStatus(ctx context.Context, arg UpdateUserAttributeDefinitionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAttributeDefinitionStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}
