// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const bumpUserTokenVersion = `-- name: BumpUserTokenVersion :exec
UPDATE users
SET token_version = token_version + 1,
    updated_at = $1
WHERE tenant_id = $2 AND id = $3
`

type BumpUserTokenVersionParams struct {
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) BumpUserTokenVersion(ctx context.Context, arg BumpUserTokenVersionParams) error {
	_, err := q.db.ExecContext(ctx, bumpUserTokenVersion, arg.UpdatedAt, arg.TenantID, arg.ID)
	return err
}

const countOtherActiveAdmins = `-- name: CountOtherActiveAdmins :one
SELECT COUNT(*) FROM users
WHERE tenant_id = $1 AND role = $2 AND status = $3 AND id <> $4
`

type CountOtherActiveAdminsParams struct {
	TenantID string
	Role     string
	Status   string
	ID       string
}

// How many administrators would remain if this one were demoted or
// disabled. Scoped to the tenant: each tenant administers itself, so another
// tenant's administrators are not a reason to let this one lock itself out.
func (q *Queries) CountOtherActiveAdmins(ctx context.Context, arg CountOtherActiveAdminsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOtherActiveAdmins,
		arg.TenantID,
		arg.Role,
		arg.Status,
		arg.ID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE tenant_id = $1
`

func (q *Queries) CountUsers(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByOrganization = `-- name: CountUsersByOrganization :one
SELECT COUNT(*) FROM users WHERE tenant_id = $1 AND organization_id = $2
`

type CountUsersByOrganizationParams struct {
	TenantID       string
	OrganizationID *string
}

func (q *Queries) CountUsersByOrganization(ctx context.Context, arg CountUsersByOrganizationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByOrganization, arg.TenantID, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersPerOrganization = `-- name: CountUsersPerOrganization :many
SELECT organization_id, COUNT(*) AS member_count
FROM users
WHERE tenant_id = $1 AND organization_id IS NOT NULL
GROUP BY organization_id
`

type CountUsersPerOrganizationRow struct {
	OrganizationID *string
	MemberCount    int64
}

// Member counts for a whole organization listing, in one round trip rather
// than one per organization.
func (q *Queries) CountUsersPerOrganization(ctx context.Context, tenantID string) ([]CountUsersPerOrganizationRow, error) {
	rows, err := q.db.QueryContext(ctx, countUsersPerOrganization, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUsersPerOrganizationRow{}
	for rows.Next() {
		var i CountUsersPerOrganizationRow
		if err := rows.Scan(&i.OrganizationID, &i.MemberCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, tenant_id, username, display_name, password_hash, phone, email,
    role, status, organization_id, token_version, source,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateUserParams struct {
	ID             string
	TenantID       string
	Username       string
	DisplayName    string
	PasswordHash   string
	Phone          string
	Email          string
	Role           string
	Status         string
	OrganizationID *string
	TokenVersion   int64
	Source         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Phone,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.OrganizationID,
		arg.TokenVersion,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, created_at, updated_at FROM users WHERE tenant_id = $1 AND id = $2 LIMIT 1
`

type GetUserByIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, arg.TenantID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.OrganizationID,
		&i.TokenVersion,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, tenant_id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, created_at, updated_at FROM users WHERE tenant_id = $1 AND username = $2 LIMIT 1
`

type GetUserByUsernameParams struct {
	TenantID string
	Username string
}

func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, arg.TenantID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.OrganizationID,
		&i.TokenVersion,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, tenant_id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, created_at, updated_at FROM users WHERE tenant_id = $1 AND id = ANY($2::text[])
`

type ListUsersByIDsParams struct {
	TenantID string
	Column2  []string
}

func (q *Queries) ListUsersByIDs(ctx context.Context, arg ListUsersByIDsParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByIDs, arg.TenantID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Phone,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.OrganizationID,
			&i.TokenVersion,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1,
    token_version = token_version + 1,
    updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UpdatedAt    time.Time
	TenantID     string
	ID           string
}

// Changing a password invalidates every token issued before it.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword,
		arg.PasswordHash,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET display_name = $1,
    phone = $2,
    email = $3,
    organization_id = $4,
    role = $5,
    updated_at = $6
WHERE tenant_id = $7 AND id = $8
`

type UpdateUserProfileParams struct {
	DisplayName    string
	Phone          string
	Email          string
	OrganizationID *string
	Role           string
	UpdatedAt      time.Time
	TenantID       string
	ID             string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Phone,
		arg.Email,
		arg.OrganizationID,
		arg.Role,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = $1,
    token_version = CASE WHEN $1 = 'DISABLED'
                         THEN token_version + 1
                         ELSE token_version END,
    updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateUserStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

// Disabling bumps token_version so any live session stops working at once.
func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}
