// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"strings"

	dbtime "github.com/paraview/keylite/internal/store/dbtime"
)

const bumpUserTokenVersion = `-- name: BumpUserTokenVersion :exec
UPDATE users
SET token_version = token_version + 1,
    updated_at = ?
WHERE id = ?
`

type BumpUserTokenVersionParams struct {
	UpdatedAt dbtime.Time
	ID        string
}

func (q *Queries) BumpUserTokenVersion(ctx context.Context, arg BumpUserTokenVersionParams) error {
	_, err := q.db.ExecContext(ctx, bumpUserTokenVersion, arg.UpdatedAt, arg.ID)
	return err
}

const clearUsersOrganization = `-- name: ClearUsersOrganization :exec
UPDATE users SET organization_id = NULL, updated_at = ? WHERE organization_id = ?
`

type ClearUsersOrganizationParams struct {
	UpdatedAt      dbtime.Time
	OrganizationID *string
}

func (q *Queries) ClearUsersOrganization(ctx context.Context, arg ClearUsersOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, clearUsersOrganization, arg.UpdatedAt, arg.OrganizationID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByOrganization = `-- name: CountUsersByOrganization :one
SELECT COUNT(*) FROM users WHERE organization_id = ?
`

func (q *Queries) CountUsersByOrganization(ctx context.Context, organizationID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = ?
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, username, display_name, password_hash, phone, email,
    role, status, organization_id, token_version, source,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID             string
	Username       string
	DisplayName    string
	PasswordHash   string
	Phone          string
	Email          string
	Role           string
	Status         string
	OrganizationID *string
	TokenVersion   int64
	Source         string
	CreatedAt      dbtime.Time
	UpdatedAt      dbtime.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Phone,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.OrganizationID,
		arg.TokenVersion,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.OrganizationID,
		&i.TokenVersion,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, created_at, updated_at FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.OrganizationID,
		&i.TokenVersion,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, username, display_name, password_hash, phone, email, role, status, organization_id, token_version, source, created_at, updated_at FROM users WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListUsersByIDs(ctx context.Context, ids []string) ([]User, error) {
	query := listUsersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Phone,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.OrganizationID,
			&i.TokenVersion,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?,
    token_version = token_version + 1,
    updated_at = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UpdatedAt    dbtime.Time
	ID           string
}

// Changing a password invalidates every token issued before it.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET display_name = ?,
    phone = ?,
    email = ?,
    organization_id = ?,
    role = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUserProfileParams struct {
	DisplayName    string
	Phone          string
	Email          string
	OrganizationID *string
	Role           string
	UpdatedAt      dbtime.Time
	ID             string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Phone,
		arg.Email,
		arg.OrganizationID,
		arg.Role,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = ?,
    token_version = CASE WHEN ? = 'DISABLED' THEN token_version + 1 ELSE token_version END,
    updated_at = ?
WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status    string
	Column2   interface{}
	UpdatedAt dbtime.Time
	ID        string
}

// Disabling bumps token_version so any live session stops working at once.
func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus,
		arg.Status,
		arg.Column2,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
