// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const claimDueWebhookDeliveries = `-- name: ClaimDueWebhookDeliveries :many
SELECT id, tenant_id, subscription_id, event_type, payload, status, attempts, last_error, last_status, next_attempt_at, created_at, delivered_at FROM webhook_deliveries
WHERE tenant_id = $1
  AND status = 'PENDING'
  AND next_attempt_at <= $2
ORDER BY next_attempt_at
LIMIT $3
FOR UPDATE SKIP LOCKED
`

type ClaimDueWebhookDeliveriesParams struct {
	TenantID      string
	NextAttemptAt *time.Time
	Limit         int32
}

// What is due, oldest first, claimed so two workers cannot take the same row.
//
// FOR UPDATE SKIP LOCKED rather than a status flag written in advance: a
// claim that is a write is a claim that outlives a crash, and a delivery
// stuck in "SENDING" because a process died mid-attempt is a delivery
// nothing will ever retry. Here the lock disappears with the transaction.
//
// Not tenant-scoped, and it is the only sweep query that is not: the worker
// runs per tenant and passes its own id. See internal/webhook/dispatcher.go.
func (q *Queries) ClaimDueWebhookDeliveries(ctx context.Context, arg ClaimDueWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, claimDueWebhookDeliveries, arg.TenantID, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.LastStatus,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingSnapshotDeliveries = `-- name: CountPendingSnapshotDeliveries :one
SELECT count(*) FROM webhook_deliveries
WHERE tenant_id = $1 AND subscription_id = $2
  AND status = 'PENDING'
  AND event_type LIKE 'sync.%'
`

type CountPendingSnapshotDeliveriesParams struct {
	TenantID       string
	SubscriptionID string
}

// How much of a snapshot is still queued for one subscription.
//
// The guard against two snapshots at once. Asking the queue rather than
// keeping a "running" flag is deliberate: a flag needs clearing, and a
// process that dies mid-snapshot would leave one set forever with nothing
// to notice. The queue empties on its own, whether the deliveries succeed
// or are given up on.
func (q *Queries) CountPendingSnapshotDeliveries(ctx context.Context, arg CountPendingSnapshotDeliveriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingSnapshotDeliveries, arg.TenantID, arg.SubscriptionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :exec
INSERT INTO webhook_subscriptions (
    id, tenant_id, name, url, secret, events, headers, status, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, 'ACTIVE', $8, $8)
`

type CreateWebhookSubscriptionParams struct {
	ID        string
	TenantID  string
	Name      string
	Url       string
	Secret    string
	Events    string
	Headers   string
	CreatedAt time.Time
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookSubscription,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Headers,
		arg.CreatedAt,
	)
	return err
}

const deleteOldWebhookDeliveries = `-- name: DeleteOldWebhookDeliveries :exec
DELETE FROM webhook_deliveries
WHERE tenant_id = $1 AND created_at < $2
`

type DeleteOldWebhookDeliveriesParams struct {
	TenantID  string
	CreatedAt time.Time
}

// Past the retention window, whatever state it reached.
//
// Pending used to be excluded, on the reasoning that a row still waiting is
// a row with work left. At this age it is not: five attempts span under half
// an hour, so anything pending thirty days later is pending against a
// subscription that was disabled while it was queued — the worker skips
// those without recording an attempt, so they are never marked failed and
// nothing else would ever remove them. Excluding them meant one forgotten
// subscription grew this table for the life of the deployment.
func (q *Queries) DeleteOldWebhookDeliveries(ctx context.Context, arg DeleteOldWebhookDeliveriesParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldWebhookDeliveries, arg.TenantID, arg.CreatedAt)
	return err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :exec
DELETE FROM webhook_subscriptions
WHERE tenant_id = $1 AND id = $2
`

type DeleteWebhookSubscriptionParams struct {
	TenantID string
	ID       string
}

// Deleted rather than disabled, like a SCIM credential and unlike an
// account: what the audit trail refers to is the event, not the row.
func (q *Queries) DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookSubscription, arg.TenantID, arg.ID)
	return err
}

const enqueueWebhookDelivery = `-- name: EnqueueWebhookDelivery :exec
INSERT INTO webhook_deliveries (
    id, tenant_id, subscription_id, event_type, payload,
    status, next_attempt_at, created_at
) VALUES ($1, $2, $3, $4, $5, 'PENDING', $6, $6)
`

type EnqueueWebhookDeliveryParams struct {
	ID             string
	TenantID       string
	SubscriptionID string
	EventType      string
	Payload        string
	NextAttemptAt  *time.Time
}

func (q *Queries) EnqueueWebhookDelivery(ctx context.Context, arg EnqueueWebhookDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, enqueueWebhookDelivery,
		arg.ID,
		arg.TenantID,
		arg.SubscriptionID,
		arg.EventType,
		arg.Payload,
		arg.NextAttemptAt,
	)
	return err
}

const getWebhookSubscription = `-- name: GetWebhookSubscription :one
SELECT id, tenant_id, name, url, secret, events, status, created_at, updated_at, previous_secret, previous_secret_expires_at, headers FROM webhook_subscriptions
WHERE tenant_id = $1 AND id = $2
`

type GetWebhookSubscriptionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetWebhookSubscription(ctx context.Context, arg GetWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRowContext(ctx, getWebhookSubscription, arg.TenantID, arg.ID)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousSecret,
		&i.PreviousSecretExpiresAt,
		&i.Headers,
	)
	return i, err
}

const listActiveWebhookSubscriptions = `-- name: ListActiveWebhookSubscriptions :many
SELECT id, tenant_id, name, url, secret, events, status, created_at, updated_at, previous_secret, previous_secret_expires_at, headers FROM webhook_subscriptions
WHERE tenant_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) ListActiveWebhookSubscriptions(ctx context.Context, tenantID string) ([]WebhookSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhookSubscriptions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PreviousSecret,
			&i.PreviousSecretExpiresAt,
			&i.Headers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, tenant_id, subscription_id, event_type, payload, status, attempts, last_error, last_status, next_attempt_at, created_at, delivered_at FROM webhook_deliveries
WHERE tenant_id = $1 AND subscription_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListWebhookDeliveriesParams struct {
	TenantID       string
	SubscriptionID string
	Limit          int32
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookDeliveries, arg.TenantID, arg.SubscriptionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.LastStatus,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT id, tenant_id, name, url, secret, events, status, created_at, updated_at, previous_secret, previous_secret_expires_at, headers FROM webhook_subscriptions
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookSubscriptions(ctx context.Context, tenantID string) ([]WebhookSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookSubscriptions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PreviousSecret,
			&i.PreviousSecretExpiresAt,
			&i.Headers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookAttemptFailed = `-- name: MarkWebhookAttemptFailed :exec
UPDATE webhook_deliveries
SET status = $1,
    attempts = attempts + 1,
    last_status = $2,
    last_error = $3,
    next_attempt_at = $4
WHERE tenant_id = $5 AND id = $6
`

type MarkWebhookAttemptFailedParams struct {
	Status        string
	LastStatus    sql.NullInt32
	LastError     string
	NextAttemptAt *time.Time
	TenantID      string
	ID            string
}

// One failed attempt, with when to try again. A NULL next_attempt_at and
// status FAILED is the end of the road.
func (q *Queries) MarkWebhookAttemptFailed(ctx context.Context, arg MarkWebhookAttemptFailedParams) error {
	_, err := q.db.ExecContext(ctx, markWebhookAttemptFailed,
		arg.Status,
		arg.LastStatus,
		arg.LastError,
		arg.NextAttemptAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE webhook_deliveries
SET status = 'DELIVERED',
    attempts = attempts + 1,
    last_status = $1,
    last_error = '',
    next_attempt_at = NULL,
    delivered_at = $2
WHERE tenant_id = $3 AND id = $4
`

type MarkWebhookDeliveredParams struct {
	LastStatus  sql.NullInt32
	DeliveredAt *time.Time
	TenantID    string
	ID          string
}

func (q *Queries) MarkWebhookDelivered(ctx context.Context, arg MarkWebhookDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, markWebhookDelivered,
		arg.LastStatus,
		arg.DeliveredAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const rotateWebhookSubscriptionSecret = `-- name: RotateWebhookSubscriptionSecret :exec
UPDATE webhook_subscriptions
SET secret = $1,
    previous_secret = secret,
    previous_secret_expires_at = $2,
    updated_at = $3
WHERE tenant_id = $4 AND id = $5
`

type RotateWebhookSubscriptionSecretParams struct {
	Secret                  string
	PreviousSecretExpiresAt *time.Time
	UpdatedAt               time.Time
	TenantID                string
	ID                      string
}

// The old key moves aside rather than being discarded, and is sent alongside
// the new one until it expires. Portico produces the signature and the
// receiver verifies it, so the receiver is the side that needs a window in
// which to deploy the new secret.
func (q *Queries) RotateWebhookSubscriptionSecret(ctx context.Context, arg RotateWebhookSubscriptionSecretParams) error {
	_, err := q.db.ExecContext(ctx, rotateWebhookSubscriptionSecret,
		arg.Secret,
		arg.PreviousSecretExpiresAt,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const setWebhookSubscriptionStatus = `-- name: SetWebhookSubscriptionStatus :exec
UPDATE webhook_subscriptions
SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type SetWebhookSubscriptionStatusParams struct {
	Status    string
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) SetWebhookSubscriptionStatus(ctx context.Context, arg SetWebhookSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setWebhookSubscriptionStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateWebhookSubscription = `-- name: UpdateWebhookSubscription :exec
UPDATE webhook_subscriptions
SET name = $1, url = $2, events = $3, headers = $4, updated_at = $5
WHERE tenant_id = $6 AND id = $7
`

type UpdateWebhookSubscriptionParams struct {
	Name      string
	Url       string
	Events    string
	Headers   string
	UpdatedAt time.Time
	TenantID  string
	ID        string
}

func (q *Queries) UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookSubscription,
		arg.Name,
		arg.Url,
		arg.Events,
		arg.Headers,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}
