// Package docs serves the manual from inside the binary, so the pages an
// operator reads are necessarily the pages for the version they are running.
//
// A documentation site hosted somewhere else drifts from the releases people
// actually have, and the failure mode is somebody following instructions for
// a version they are not running — which reads as the product being wrong
// rather than the page being old.
//
// The embedded directory must exist at compile time even when the site has
// not been built, which is why site/ carries a committed .gitkeep and this
// package tolerates an empty tree: a `go build` in a fresh clone still
// succeeds, and the server says plainly that the manual is missing rather
// than serving a blank page. The same arrangement as internal/web.
package docs

import (
	"embed"
	"errors"
	"io/fs"
	"net/http"
	"path"
	"strings"
)

//go:embed all:site
var embedded embed.FS

// Prefix is where the manual is mounted. It is a constant rather than a
// caller's choice because the built site contains links generated against
// it: moving the mount without rebuilding would serve a site whose own
// navigation points somewhere else.
const Prefix = "/docs"

// Available reports whether a built manual is present.
func Available() bool {
	_, err := fs.Stat(assets(), "index.html")
	return err == nil
}

func assets() fs.FS {
	sub, err := fs.Sub(embedded, "site")
	if err != nil {
		// The directory is embedded above, so this cannot fail in a build
		// that compiled.
		panic("docs: embedded site is missing: " + err.Error())
	}
	return sub
}

// Handler serves the built manual under Prefix.
//
// Unknown paths return 404 rather than falling back to the index, which is
// the opposite of what the application shell does and for the opposite
// reason: the application has client-side routes that only exist in the
// browser, and a manual has exactly the pages that were built. Handing back
// the home page for a mistyped address would tell a reader the page exists
// and is about something else.
func Handler() http.Handler {
	if !Available() {
		return http.HandlerFunc(notBuilt)
	}

	files := assets()
	fileServer := http.StripPrefix(Prefix, http.FileServer(http.FS(files)))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requested := strings.TrimPrefix(path.Clean(r.URL.Path), Prefix)
		requested = strings.TrimPrefix(requested, "/")
		if requested == "" || requested == "." {
			requested = "index.html"
		}
		// Directory URLs: /docs/ldap/ is a directory holding index.html.
		if !strings.Contains(path.Base(requested), ".") {
			requested = path.Join(requested, "index.html")
		}

		if _, err := fs.Stat(files, requested); err != nil {
			if !errors.Is(err, fs.ErrNotExist) {
				http.Error(w, "internal error", http.StatusInternalServerError)
				return
			}
			http.NotFound(w, r)
			return
		}

		// Everything here is regenerated by a build rather than
		// content-hashed, so none of it can be cached indefinitely the way a
		// hashed asset can. no-cache stores it and revalidates, which is what
		// makes a corrected page arrive after an upgrade.
		w.Header().Set("Cache-Control", "no-cache")
		fileServer.ServeHTTP(w, r)
	})
}

func notBuilt(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(http.StatusNotFound)
	_, _ = w.Write([]byte(
		"The Portico manual was not included in this build.\n\n" +
			"Build it with:\n" +
			"  ./hack/build-docs.sh\n" +
			"then rebuild the server binary.\n\n" +
			"It is also readable as Markdown in docs/ in the repository.\n",
	))
}

// LocalePath maps one of Portico's locales onto the manual's own language
// prefix, so a link from a Chinese console lands on the Chinese manual.
//
// The two vocabularies are deliberately not the same: Portico speaks BCP 47
// tags because that is what a directory sends, and the manual is built with
// short prefixes because they are what a person sees in a URL. This is the
// one place they meet, and it falls back to the default rather than
// producing a path that does not exist.
func LocalePath(locale string) string {
	if strings.HasPrefix(strings.ToLower(locale), "zh") {
		return Prefix + "/zh/"
	}
	return Prefix + "/"
}
