// Package store owns database access: opening the pool, running migrations,
// and the query layer generated by sqlc.
package store

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib" // registers the "pgx" driver
	"github.com/pressly/goose/v3"

	"github.com/Paraview-RD/portico/internal/store/sqlcgen"
	"github.com/Paraview-RD/portico/migrations"
)

// Store holds the database handle and the generated query set.
type Store struct {
	db      *sql.DB
	Queries *sqlcgen.Queries
}

// Open connects to the database, applies any pending migrations, and returns
// a ready-to-use Store.
//
// dsn is a PostgreSQL connection string, in either URL form
// (postgres://user:pass@host:5432/db?sslmode=disable) or keyword form.
func Open(driver, dsn string) (*Store, error) {
	if driver != "postgres" {
		return nil, fmt.Errorf(
			"unsupported database driver %q (only \"postgres\" is implemented)", driver)
	}
	if dsn == "" {
		return nil, fmt.Errorf("database DSN is empty; set PORTICO_DB_DSN")
	}

	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, fmt.Errorf("open database: %w", err)
	}

	// Modest bounds rather than the unlimited default: an unbounded pool
	// turns a traffic spike into connection exhaustion on the database,
	// which fails far less gracefully than queueing here does.
	db.SetMaxOpenConns(25)
	db.SetMaxIdleConns(5)
	db.SetConnMaxLifetime(time.Hour)
	db.SetConnMaxIdleTime(10 * time.Minute)

	// Bounded so a wrong host fails at startup instead of hanging.
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("connect to database: %w", err)
	}

	if err := migrate(db); err != nil {
		_ = db.Close()
		return nil, err
	}

	return &Store{db: db, Queries: sqlcgen.New(db)}, nil
}

func migrate(db *sql.DB) error {
	goose.SetBaseFS(migrations.FS)
	goose.SetLogger(goose.NopLogger())

	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("set migration dialect: %w", err)
	}
	if err := goose.Up(db, "."); err != nil {
		return fmt.Errorf("apply migrations: %w", err)
	}
	return nil
}

// DB exposes the raw handle for the hand-written queries that sqlc cannot
// express, such as list endpoints with optional filters.
func (s *Store) DB() *sql.DB { return s.db }

// Close releases the connection pool.
func (s *Store) Close() error { return s.db.Close() }

// WithTx runs fn inside a transaction, rolling back on error or panic.
func (s *Store) WithTx(fn func(*sqlcgen.Queries) error) error {
	tx, err := s.db.Begin()
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}
	defer func() {
		// Rollback after a successful Commit is a no-op, so this is safe as
		// an unconditional cleanup.
		_ = tx.Rollback()
	}()

	if err := fn(sqlcgen.New(tx)); err != nil {
		return err
	}
	return tx.Commit()
}

// Now returns the current time in UTC, truncated to the microsecond that
// PostgreSQL stores, so a value written and read back compares equal.
func Now() time.Time { return time.Now().UTC().Truncate(time.Microsecond) }

// AfterEverything is a timestamp no stored row can hold, used as the opening
// cursor of a newest-first page.
//
// It exists so that "the first page" and "the page after this row" are the
// same query rather than two, which is what keeps a paging bug from living
// in only one of them. Any real created_at compares below it.
var AfterEverything = time.Date(9999, 12, 31, 23, 59, 59, 0, time.UTC)
