// Package store owns database access: opening the connection, running
// migrations, and the query layer generated by sqlc.
//
// Timestamps are stored as ISO 8601 text, which keeps the database readable
// from the sqlite3 CLI and sorts correctly. The conversion that this costs
// lives in the dbtime package rather than being spread across callers.
package store

import (
	"database/sql"
	"fmt"
	"net/url"
	"strings"

	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite" // pure-Go driver: no cgo, so the binary cross-compiles

	"github.com/paraview/portico/internal/store/dbtime"
	"github.com/paraview/portico/internal/store/sqlcgen"
	"github.com/paraview/portico/migrations"
)

// Store holds the database handle and the generated query set.
type Store struct {
	db      *sql.DB
	Queries *sqlcgen.Queries
}

// Open connects to the database, applies any pending migrations, and returns
// a ready-to-use Store.
func Open(driver, dsn string) (*Store, error) {
	if driver != "sqlite" {
		return nil, fmt.Errorf("unsupported database driver %q (only \"sqlite\" is implemented)", driver)
	}

	db, err := sql.Open(driver, sqliteDSN(dsn))
	if err != nil {
		return nil, fmt.Errorf("open database: %w", err)
	}

	// SQLite permits only one writer. Serializing access here avoids
	// SQLITE_BUSY under concurrent writes; reads are fast enough at this
	// scale that the lost parallelism does not matter.
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)
	db.SetConnMaxLifetime(0)

	if err := db.Ping(); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("connect to database: %w", err)
	}

	if err := migrate(db); err != nil {
		_ = db.Close()
		return nil, err
	}

	return &Store{db: db, Queries: sqlcgen.New(db)}, nil
}

// sqliteDSN appends the pragmas the application relies on, preserving any
// the caller already set.
func sqliteDSN(dsn string) string {
	// An in-memory DSN carries its own parameters; leave it alone.
	if strings.HasPrefix(dsn, "file:") || strings.Contains(dsn, ":memory:") {
		return dsn
	}

	params := url.Values{}
	// Foreign keys are off by default in SQLite; the schema relies on them.
	params.Set("_pragma", "foreign_keys(1)")
	// WAL lets readers proceed during a write, which matters even with a
	// single writer connection.
	params.Add("_pragma", "journal_mode(WAL)")
	// Wait rather than failing immediately if the file is briefly locked by
	// another process (e.g. a CLI session left open).
	params.Add("_pragma", "busy_timeout(5000)")

	return dsn + "?" + params.Encode()
}

func migrate(db *sql.DB) error {
	goose.SetBaseFS(migrations.FS)
	goose.SetLogger(goose.NopLogger())

	if err := goose.SetDialect("sqlite3"); err != nil {
		return fmt.Errorf("set migration dialect: %w", err)
	}
	if err := goose.Up(db, "."); err != nil {
		return fmt.Errorf("apply migrations: %w", err)
	}
	return nil
}

// DB exposes the raw handle for the hand-written queries that sqlc cannot
// express, such as list endpoints with optional filters.
func (s *Store) DB() *sql.DB { return s.db }

// Close releases the database handle.
func (s *Store) Close() error { return s.db.Close() }

// WithTx runs fn inside a transaction, rolling back on error or panic.
func (s *Store) WithTx(fn func(*sqlcgen.Queries) error) error {
	tx, err := s.db.Begin()
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}
	defer func() {
		// Rollback after a successful Commit is a no-op, so this is safe
		// as an unconditional cleanup.
		_ = tx.Rollback()
	}()

	if err := fn(sqlcgen.New(tx)); err != nil {
		return err
	}
	return tx.Commit()
}

// Now returns the current time in the form the database stores.
func Now() dbtime.Time { return dbtime.Now() }
